<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Logistics\ConsigneeNotify;
use App\Models\Country;

class ConsigneeNotifySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get some countries for foreign key
        $egypt = Country::where('name', 'Egypt')->first();
        $usa = Country::where('name', 'United States')->first();
        $germany = Country::where('name', 'Germany')->first();
        $china = Country::where('name', 'China')->first();

        $consigneeNotifies = [
            [
                'party_code' => 'CNS001',
                'party_name' => 'ABC Trading Company Ltd.',
                'party_type' => 'Consignee',
                'company_registration' => 'REG123456789',
                'tax_id' => 'TAX987654321',
                'contact_person' => 'Ahmed Hassan',
                'email' => 'ahmed.hassan@abctrading.com',
                'phone' => '+20-2-1234-5678',
                'fax' => '+20-2-1234-5679',
                'address' => '123 Nile Street, Floor 5, Building A',
                'city' => 'Cairo',
                'state_province' => 'Cairo Governorate',
                'country' => 'Egypt',
                'postal_code' => '11511',
                'country_id' => $egypt?->id,
                'preferred_language' => 'ar',
                'notification_preferences' => ['email', 'sms'],
                'delivery_instructions' => 'Deliver during business hours only. Requires appointment.',
                'special_requirements' => 'Temperature-controlled storage required',
                'requires_original_docs' => true,
                'is_freight_forwarder' => false,
                'credit_rating' => 'A',
                'credit_limit' => 100000.00,
                'payment_terms' => 'Net 30 days',
                'status' => 'Active',
                'notes' => 'Reliable client with excellent payment history'
            ],
            [
                'party_code' => 'NTF001',
                'party_name' => 'Global Shipping Notifications Inc.',
                'party_type' => 'Notify Party',
                'company_registration' => 'US123456789',
                'tax_id' => 'EIN12-3456789',
                'contact_person' => 'John Smith',
                'email' => 'notifications@globalshipping.com',
                'phone' => '+1-555-123-4567',
                'fax' => '+1-555-123-4568',
                'address' => '456 Harbor Boulevard, Suite 200',
                'city' => 'Los Angeles',
                'state_province' => 'California',
                'country' => 'United States',
                'postal_code' => '90012',
                'country_id' => $usa?->id,
                'preferred_language' => 'en',
                'notification_preferences' => ['email', 'phone'],
                'delivery_instructions' => '24/7 notification service available',
                'special_requirements' => 'Immediate notification required for all status changes',
                'requires_original_docs' => false,
                'is_freight_forwarder' => true,
                'credit_rating' => 'B',
                'credit_limit' => 50000.00,
                'payment_terms' => 'Net 15 days',
                'status' => 'Active',
                'notes' => 'Primary notification partner for US operations'
            ],
            [
                'party_code' => 'BTH001',
                'party_name' => 'Mediterranean Logistics Hub',
                'party_type' => 'Both',
                'company_registration' => 'DE789123456',
                'tax_id' => 'DE123456789',
                'contact_person' => 'Klaus Mueller',
                'email' => 'klaus.mueller@medlog.de',
                'phone' => '+49-40-1234-567',
                'fax' => '+49-40-1234-568',
                'address' => 'Hafenstraße 789, Warehouse Complex B',
                'city' => 'Hamburg',
                'state_province' => 'Hamburg',
                'country' => 'Germany',
                'postal_code' => '20459',
                'country_id' => $germany?->id,
                'preferred_language' => 'en',
                'notification_preferences' => ['email', 'sms', 'phone'],
                'delivery_instructions' => 'Coordinate with port authority for container delivery',
                'special_requirements' => 'Customs clearance support required',
                'requires_original_docs' => true,
                'is_freight_forwarder' => true,
                'credit_rating' => 'A',
                'credit_limit' => 200000.00,
                'payment_terms' => 'Net 30 days',
                'status' => 'Active',
                'notes' => 'Key European distribution partner'
            ],
            [
                'party_code' => 'CNS002',
                'party_name' => 'Pharma Import Solutions',
                'party_type' => 'Consignee',
                'company_registration' => 'EG987654321',
                'tax_id' => 'TAX456789123',
                'contact_person' => 'Fatma Al-Zahra',
                'email' => 'fatma.zahra@pharmaimport.com',
                'phone' => '+20-3-987-6543',
                'fax' => '+20-3-987-6544',
                'address' => '789 Industrial Zone, Block 15',
                'city' => 'Alexandria',
                'state_province' => 'Alexandria Governorate',
                'country' => 'Egypt',
                'postal_code' => '21500',
                'country_id' => $egypt?->id,
                'preferred_language' => 'ar',
                'notification_preferences' => ['email'],
                'delivery_instructions' => 'Temperature monitoring required. Cold chain essential.',
                'special_requirements' => 'FDA-approved facility. Pharmaceutical grade handling.',
                'requires_original_docs' => true,
                'is_freight_forwarder' => false,
                'credit_rating' => 'A',
                'credit_limit' => 500000.00,
                'payment_terms' => 'Net 45 days',
                'status' => 'Active',
                'notes' => 'Specialized in pharmaceutical imports'
            ],
            [
                'party_code' => 'CNS003',
                'party_name' => 'Shanghai Electronics Co. Ltd',
                'party_type' => 'Consignee',
                'company_registration' => 'CN987654321',
                'tax_id' => 'CN123456789',
                'contact_person' => 'Wei Zhang',
                'email' => 'wei.zhang@shanghaielec.com',
                'phone' => '+86-21-1234-5678',
                'fax' => '+86-21-1234-5679',
                'address' => '168 Pudong Avenue, Technology Park',
                'city' => 'Shanghai',
                'state_province' => 'Shanghai',
                'country' => 'China',
                'postal_code' => '200120',
                'country_id' => $china?->id,
                'preferred_language' => 'en',
                'notification_preferences' => ['email', 'sms'],
                'delivery_instructions' => 'Coordinate with customs broker for electronics clearance',
                'special_requirements' => 'Anti-static handling required for electronic components',
                'requires_original_docs' => true,
                'is_freight_forwarder' => false,
                'credit_rating' => 'B',
                'credit_limit' => 75000.00,
                'payment_terms' => 'Letter of Credit',
                'status' => 'Active',
                'notes' => 'Major electronics manufacturer and importer'
            ],
            [
                'party_code' => 'NTF002',
                'party_name' => 'Red Sea Freight Forwarders',
                'party_type' => 'Notify Party',
                'company_registration' => 'EG555666777',
                'tax_id' => 'TAX777888999',
                'contact_person' => 'Omar Ibrahim',
                'email' => 'omar.ibrahim@redseafreight.com',
                'phone' => '+20-65-444-5555',
                'fax' => '+20-65-444-5556',
                'address' => '321 Port Said Street, Freight District',
                'city' => 'Suez',
                'state_province' => 'Suez Governorate',
                'country' => 'Egypt',
                'postal_code' => '43512',
                'country_id' => $egypt?->id,
                'preferred_language' => 'ar',
                'notification_preferences' => ['email', 'phone'],
                'delivery_instructions' => 'Immediate notification for Suez Canal transit',
                'special_requirements' => 'Real-time tracking updates required',
                'requires_original_docs' => false,
                'is_freight_forwarder' => true,
                'credit_rating' => 'B',
                'credit_limit' => 25000.00,
                'payment_terms' => 'Net 21 days',
                'status' => 'Active',
                'notes' => 'Specialized in Suez Canal operations'
            ],
            [
                'party_code' => 'CNS004',
                'party_name' => 'Automotive Parts Distribution',
                'party_type' => 'Consignee',
                'company_registration' => 'EG111222333',
                'tax_id' => 'TAX333444555',
                'contact_person' => 'Mohamed Farid',
                'email' => 'mohamed.farid@autoparts.com',
                'phone' => '+20-2-666-7777',
                'fax' => '+20-2-666-7778',
                'address' => '999 Industrial Road, Auto Zone',
                'city' => 'Giza',
                'state_province' => 'Giza Governorate',
                'country' => 'Egypt',
                'postal_code' => '12345',
                'country_id' => $egypt?->id,
                'preferred_language' => 'ar',
                'notification_preferences' => ['sms'],
                'delivery_instructions' => 'Schedule delivery to avoid peak traffic hours',
                'special_requirements' => 'Heavy machinery for unloading available on-site',
                'requires_original_docs' => true,
                'is_freight_forwarder' => false,
                'credit_rating' => 'C',
                'credit_limit' => 30000.00,
                'payment_terms' => 'Cash on Delivery',
                'status' => 'Active',
                'notes' => 'Automotive parts distributor for local market'
            ],
            [
                'party_code' => 'BTH002',
                'party_name' => 'International Trade Solutions',
                'party_type' => 'Both',
                'company_registration' => 'EG444555666',
                'tax_id' => 'TAX666777888',
                'contact_person' => 'Sarah Ahmed',
                'email' => 'sarah.ahmed@inttrade.com',
                'phone' => '+20-2-888-9999',
                'fax' => '+20-2-888-9998',
                'address' => '555 Business District, Tower C, Floor 12',
                'city' => 'New Cairo',
                'state_province' => 'Cairo Governorate',
                'country' => 'Egypt',
                'postal_code' => '11835',
                'country_id' => $egypt?->id,
                'preferred_language' => 'en',
                'notification_preferences' => ['email', 'sms', 'phone'],
                'delivery_instructions' => 'Full service logistics coordination required',
                'special_requirements' => 'Customs clearance and documentation support',
                'requires_original_docs' => true,
                'is_freight_forwarder' => true,
                'credit_rating' => 'A',
                'credit_limit' => 150000.00,
                'payment_terms' => 'Net 30 days',
                'status' => 'Active',
                'notes' => 'Comprehensive international trade services'
            ],
            [
                'party_code' => 'CNS005',
                'party_name' => 'Inactive Test Company',
                'party_type' => 'Consignee',
                'company_registration' => 'TEST123',
                'tax_id' => 'TESTTAX123',
                'contact_person' => 'Test Person',
                'email' => 'test@inactive.com',
                'phone' => '+20-2-000-0000',
                'address' => 'Test Address',
                'city' => 'Test City',
                'country' => 'Egypt',
                'country_id' => $egypt?->id,
                'preferred_language' => 'en',
                'notification_preferences' => ['email'],
                'requires_original_docs' => false,
                'is_freight_forwarder' => false,
                'status' => 'Inactive',
                'notes' => 'Inactive company for testing purposes'
            ]
        ];

        foreach ($consigneeNotifies as $party) {
            ConsigneeNotify::create($party);
        }

        $this->command->info('ConsigneeNotify seeder completed successfully!');
    }
}
