<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\ContainerLoading;
use App\Models\Country;

class ContainerLoadingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get some countries for foreign key
        $egypt = Country::where('name', 'Egypt')->first();
        $usa = Country::where('name', 'United States')->first();
        $germany = Country::where('name', 'Germany')->first();
        $uae = Country::where('name', 'United Arab Emirates')->first();
        $china = Country::where('name', 'China')->first();

        $loadingPoints = [
            [
                'loading_point_code' => 'LP001',
                'loading_point_name' => 'Cairo Container Freight Station',
                'facility_type' => 'CFS',
                'operator_name' => 'Egyptian Container Services Co.',
                'contact_person' => 'Ahmed Mahmoud',
                'phone' => '+20-2-2345-6789',
                'email' => 'ahmed.mahmoud@ecscfs.com',
                'address' => '123 Industrial Zone, 10th of Ramadan City',
                'city' => 'Cairo',
                'country' => 'Egypt',
                'country_id' => $egypt?->id,
                'postal_code' => '11835',
                'latitude' => 30.0444,
                'longitude' => 31.2357,
                'operating_hours' => ['monday' => '06:00-18:00', 'general' => '6 AM - 6 PM'],
                'container_types_handled' => ['20GP', '40GP', '40HC', '20RF'],
                'max_containers_per_day' => 150,
                'equipment_available' => ['Mobile Crane', 'Reach Stacker', 'Forklift', 'Weighbridge'],
                'services_offered' => ['Container Stuffing', 'Container Destuffing', 'Storage', 'Customs Inspection'],
                'storage_rate_per_day' => 45.00,
                'stuffing_rate' => 250.00,
                'destuffing_rate' => 200.00,
                'has_security' => true,
                'has_cctv' => true,
                'requires_appointment' => true,
                'advance_booking_hours' => 24,
                'access_instructions' => 'Enter through main gate, present booking confirmation and ID.',
                'safety_requirements' => 'Hard hats and safety vests required in operational areas.',
                'status' => 'Active',
                'notes' => 'Main CFS facility serving Greater Cairo area'
            ],
            [
                'loading_point_code' => 'LP002',
                'loading_point_name' => 'Alexandria Port Terminal',
                'facility_type' => 'Port Terminal',
                'operator_name' => 'Alexandria Container Terminal',
                'contact_person' => 'Mohamed El-Sayed',
                'phone' => '+20-3-4567-8901',
                'email' => 'operations@alexport.com',
                'address' => 'Alexandria Port, Eastern Harbor',
                'city' => 'Alexandria',
                'country' => 'Egypt',
                'country_id' => $egypt?->id,
                'postal_code' => '21500',
                'latitude' => 31.2156,
                'longitude' => 29.9553,
                'operating_hours' => ['general' => '24/7'],
                'container_types_handled' => ['20GP', '40GP', '40HC', '45HC', '20RF', '40RF'],
                'max_containers_per_day' => 500,
                'equipment_available' => ['Ship-to-Shore Crane', 'RTG Crane', 'Reach Stacker', 'Forklift', 'Weighbridge', 'Scanner'],
                'services_offered' => ['Container Stuffing', 'Container Destuffing', 'Storage', 'Customs Inspection', 'Trans-loading'],
                'storage_rate_per_day' => 35.00,
                'stuffing_rate' => 180.00,
                'destuffing_rate' => 150.00,
                'has_security' => true,
                'has_cctv' => true,
                'requires_appointment' => false,
                'advance_booking_hours' => 12,
                'access_instructions' => 'Port security clearance required. Follow terminal procedures.',
                'safety_requirements' => 'Full PPE required. Safety induction mandatory for first-time visitors.',
                'status' => 'Active',
                'notes' => 'Major port terminal with direct vessel access'
            ],
            [
                'loading_point_code' => 'LP003',
                'loading_point_name' => 'Los Angeles Warehouse Complex',
                'facility_type' => 'Warehouse',
                'operator_name' => 'Pacific Logistics Inc.',
                'contact_person' => 'John Anderson',
                'phone' => '+1-310-555-0123',
                'email' => 'john.anderson@pacificlogistics.com',
                'address' => '2500 Harbor Boulevard, Warehouse District',
                'city' => 'Los Angeles',
                'country' => 'United States',
                'country_id' => $usa?->id,
                'postal_code' => '90731',
                'latitude' => 33.7367,
                'longitude' => -118.2922,
                'operating_hours' => ['general' => 'Mon-Fri 7 AM - 7 PM, Sat 8 AM - 4 PM'],
                'container_types_handled' => ['20GP', '40GP', '40HC', '45HC'],
                'max_containers_per_day' => 75,
                'equipment_available' => ['Forklift', 'Side Loader', 'Weighbridge'],
                'services_offered' => ['Container Stuffing', 'Container Destuffing', 'Storage', 'Cargo Consolidation'],
                'storage_rate_per_day' => 85.00,
                'stuffing_rate' => 350.00,
                'destuffing_rate' => 300.00,
                'has_security' => true,
                'has_cctv' => true,
                'requires_appointment' => true,
                'advance_booking_hours' => 48,
                'access_instructions' => 'Schedule appointment minimum 48 hours in advance. Dock assignment upon arrival.',
                'safety_requirements' => 'Safety orientation required. No smoking policy strictly enforced.',
                'status' => 'Active',
                'notes' => 'Premium warehouse facility with temperature-controlled zones'
            ],
            [
                'loading_point_code' => 'LP004',
                'loading_point_name' => 'Hamburg Container Depot',
                'facility_type' => 'Depot',
                'operator_name' => 'Deutsche Container Logistik GmbH',
                'contact_person' => 'Klaus Weber',
                'phone' => '+49-40-1234-567',
                'email' => 'klaus.weber@dclogistik.de',
                'address' => 'Hafenstraße 456, Container Terminal',
                'city' => 'Hamburg',
                'country' => 'Germany',
                'country_id' => $germany?->id,
                'postal_code' => '20459',
                'latitude' => 53.5439,
                'longitude' => 9.9678,
                'operating_hours' => ['general' => 'Mon-Fri 6 AM - 8 PM, Sat 8 AM - 2 PM'],
                'container_types_handled' => ['20GP', '40GP', '40HC', '45HC', '20RF', '40RF', '20OT', '40OT'],
                'max_containers_per_day' => 200,
                'equipment_available' => ['Reach Stacker', 'Top Loader', 'Forklift', 'Mobile Crane', 'Weighbridge'],
                'services_offered' => ['Storage', 'Customs Inspection', 'Documentation', 'Container Stuffing'],
                'storage_rate_per_day' => 65.00,
                'stuffing_rate' => 280.00,
                'destuffing_rate' => 220.00,
                'has_security' => true,
                'has_cctv' => true,
                'requires_appointment' => true,
                'advance_booking_hours' => 24,
                'access_instructions' => 'EU customs documentation required. Follow German port regulations.',
                'safety_requirements' => 'ISO safety standards compliance mandatory.',
                'status' => 'Active',
                'notes' => 'European hub facility with excellent rail connections'
            ],
            [
                'loading_point_code' => 'LP005',
                'loading_point_name' => 'Dubai Jebel Ali Container Yard',
                'facility_type' => 'Container Yard',
                'operator_name' => 'Emirates Container Facilities LLC',
                'contact_person' => 'Omar Al-Rashid',
                'phone' => '+971-4-881-5555',
                'email' => 'omar.rashid@ecfuae.com',
                'address' => 'Jebel Ali Port, South Terminal',
                'city' => 'Dubai',
                'country' => 'United Arab Emirates',
                'country_id' => $uae?->id,
                'postal_code' => '17000',
                'latitude' => 25.0124,
                'longitude' => 55.1003,
                'operating_hours' => ['general' => '24/7'],
                'container_types_handled' => ['20GP', '40GP', '40HC', '45HC', '20RF', '40RF'],
                'max_containers_per_day' => 300,
                'equipment_available' => ['RTG Crane', 'Reach Stacker', 'Forklift', 'Weighbridge', 'Scanner'],
                'services_offered' => ['Storage', 'Container Stuffing', 'Container Destuffing', 'Trans-loading', 'Documentation'],
                'storage_rate_per_day' => 55.00,
                'stuffing_rate' => 220.00,
                'destuffing_rate' => 180.00,
                'has_security' => true,
                'has_cctv' => true,
                'requires_appointment' => false,
                'advance_booking_hours' => 6,
                'access_instructions' => 'RFID access cards required. Follow JAFZA regulations.',
                'safety_requirements' => 'UAE safety standards. High-visibility clothing mandatory.',
                'status' => 'Active',
                'notes' => 'Strategic location for Middle East and South Asia trade'
            ],
            [
                'loading_point_code' => 'LP006',
                'loading_point_name' => 'Shanghai Manufacturing Plant',
                'facility_type' => 'Factory',
                'operator_name' => 'Shanghai Electronics Manufacturing Co.',
                'contact_person' => 'Li Wei',
                'phone' => '+86-21-5555-6666',
                'email' => 'li.wei@shanghaielec.com',
                'address' => '888 Industrial Park Road, Pudong District',
                'city' => 'Shanghai',
                'country' => 'China',
                'country_id' => $china?->id,
                'postal_code' => '201203',
                'latitude' => 31.2304,
                'longitude' => 121.4737,
                'operating_hours' => ['general' => 'Mon-Sat 8 AM - 6 PM'],
                'container_types_handled' => ['20GP', '40GP', '40HC'],
                'max_containers_per_day' => 50,
                'equipment_available' => ['Forklift', 'Side Loader'],
                'services_offered' => ['Container Stuffing', 'Documentation'],
                'storage_rate_per_day' => 25.00,
                'stuffing_rate' => 120.00,
                'destuffing_rate' => 100.00,
                'has_security' => true,
                'has_cctv' => false,
                'requires_appointment' => true,
                'advance_booking_hours' => 72,
                'access_instructions' => 'Factory visitor registration required. Chinese customs procedures apply.',
                'safety_requirements' => 'Factory safety briefing mandatory. No photography allowed.',
                'status' => 'Active',
                'notes' => 'Electronics manufacturing facility with direct loading capabilities'
            ],
            [
                'loading_point_code' => 'LP007',
                'loading_point_name' => 'Suez Inland Terminal',
                'facility_type' => 'Inland Terminal',
                'operator_name' => 'Suez Canal Container Terminal',
                'contact_person' => 'Mahmoud Hassan',
                'phone' => '+20-62-333-4444',
                'email' => 'mahmoud.hassan@scct.com.eg',
                'address' => 'Suez Canal Economic Zone, East Port Said',
                'city' => 'Suez',
                'country' => 'Egypt',
                'country_id' => $egypt?->id,
                'postal_code' => '42511',
                'latitude' => 30.5965,
                'longitude' => 32.2715,
                'operating_hours' => ['general' => '24/7'],
                'container_types_handled' => ['20GP', '40GP', '40HC', '45HC'],
                'max_containers_per_day' => 120,
                'equipment_available' => ['Reach Stacker', 'Forklift', 'Mobile Crane'],
                'services_offered' => ['Storage', 'Trans-loading', 'Customs Inspection'],
                'storage_rate_per_day' => 30.00,
                'stuffing_rate' => 150.00,
                'destuffing_rate' => 120.00,
                'has_security' => true,
                'has_cctv' => true,
                'requires_appointment' => true,
                'advance_booking_hours' => 12,
                'access_instructions' => 'Economic zone clearance required. Suez Canal Authority regulations apply.',
                'safety_requirements' => 'Port authority safety certification required.',
                'status' => 'Active',
                'notes' => 'Strategic location for Suez Canal transit cargo'
            ],
            [
                'loading_point_code' => 'LP008',
                'loading_point_name' => 'Inactive Test Facility',
                'facility_type' => 'Warehouse',
                'operator_name' => 'Test Operator',
                'contact_person' => 'Test Person',
                'phone' => '+20-2-000-0000',
                'email' => 'test@inactive.com',
                'address' => 'Test Address',
                'city' => 'Test City',
                'country' => 'Egypt',
                'country_id' => $egypt?->id,
                'operating_hours' => ['general' => 'Closed'],
                'container_types_handled' => ['20GP'],
                'max_containers_per_day' => 10,
                'equipment_available' => ['Forklift'],
                'services_offered' => ['Storage'],
                'has_security' => false,
                'has_cctv' => false,
                'requires_appointment' => true,
                'advance_booking_hours' => 24,
                'status' => 'Inactive',
                'notes' => 'Inactive facility for testing purposes'
            ],
            [
                'loading_point_code' => 'LP009',
                'loading_point_name' => 'Hamburg Maintenance Facility',
                'facility_type' => 'Depot',
                'operator_name' => 'Hamburg Container Services',
                'contact_person' => 'Hans Mueller',
                'phone' => '+49-40-7777-888',
                'email' => 'hans.mueller@hcs.de',
                'address' => 'Maintenance Zone, Hamburg Port',
                'city' => 'Hamburg',
                'country' => 'Germany',
                'country_id' => $germany?->id,
                'postal_code' => '20457',
                'operating_hours' => ['general' => 'Under Maintenance'],
                'container_types_handled' => ['20GP', '40GP'],
                'max_containers_per_day' => 80,
                'equipment_available' => ['Mobile Crane', 'Forklift'],
                'services_offered' => ['Storage'],
                'has_security' => true,
                'has_cctv' => true,
                'requires_appointment' => true,
                'advance_booking_hours' => 48,
                'status' => 'Maintenance',
                'notes' => 'Facility currently under maintenance - equipment upgrade in progress'
            ]
        ];

        foreach ($loadingPoints as $point) {
            ContainerLoading::create($point);
        }

        $this->command->info('ContainerLoading seeder completed successfully!');
    }
}
