<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\PortOperation;
use App\Models\Port;
use App\Models\Shipment;

class PortOperationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get some existing ports and shipments
        $ports = Port::active()->take(5)->get();
        $shipments = Shipment::take(10)->get();

        if ($ports->isEmpty()) {
            $this->command->warn('No active ports found. Please run PortSeeder first.');
            return;
        }

        $operations = [
            [
                'operation_id' => 'OP-2025-001',
                'port_id' => $ports->first()->id,
                'shipment_id' => $shipments->first()->id ?? null,
                'operation_type' => 'Loading',
                'vessel_name' => 'MSC Gülsün',
                'vessel_imo' => 'IMO9811000',
                'vessel_type' => 'Container Ship',
                'vessel_size' => 230000.00,
                'vessel_flag' => 'Panama',
                'berth_number' => 'B-12',
                'berth_assignment_time' => now()->subHours(2),
                'scheduled_arrival' => now()->subHours(4),
                'actual_arrival' => now()->subHours(3)->subMinutes(45),
                'scheduled_departure' => now()->addHours(8),
                'operation_start_time' => now()->subHours(2),
                'cargo_type' => 'Container',
                'cargo_volume' => 1850.00,
                'containers_count' => 1850,
                'container_types' => ['20ft', '40ft', '40ft HC'],
                'handling_equipment_used' => ['Container Cranes', 'Reach Stackers', 'Terminal Tractors'],
                'operator_name' => 'Ahmed Hassan',
                'pilot_required' => true,
                'pilot_name' => 'Captain Mohamed Ali',
                'tugboat_required' => true,
                'tugboat_count' => 2,
                'handling_cost' => 12500.00,
                'port_fees' => 8500.00,
                'additional_charges' => 1200.00,
                'total_cost' => 22200.00,
                'status' => 'In Progress',
                'priority' => 'High',
                'customs_cleared' => true,
                'quarantine_cleared' => true,
                'documents_complete' => true,
                'weather_conditions' => 'Clear, Wind 15 knots',
                'operation_notes' => 'Large container vessel, priority loading for European route.',
                'special_requirements' => 'Reefer containers require power connection'
            ],
            [
                'operation_id' => 'OP-2025-002',
                'port_id' => $ports->get(1)->id ?? $ports->first()->id,
                'shipment_id' => $shipments->get(1)->id ?? null,
                'operation_type' => 'Unloading',
                'vessel_name' => 'COSCO Shipping Galaxy',
                'vessel_imo' => 'IMO9795600',
                'vessel_type' => 'Container Ship',
                'vessel_size' => 147000.00,
                'vessel_flag' => 'China',
                'berth_number' => 'B-8',
                'berth_assignment_time' => now()->addHours(1),
                'scheduled_arrival' => now()->addHours(2),
                'scheduled_departure' => now()->addHours(14),
                'cargo_type' => 'Container',
                'cargo_volume' => 2100.00,
                'containers_count' => 2100,
                'container_types' => ['20ft', '40ft'],
                'handling_equipment_used' => ['Container Cranes', 'Forklifts'],
                'operator_name' => 'Sarah El-Masry',
                'pilot_required' => true,
                'tugboat_required' => true,
                'tugboat_count' => 1,
                'handling_cost' => 15600.00,
                'port_fees' => 9200.00,
                'additional_charges' => 800.00,
                'total_cost' => 25600.00,
                'status' => 'Scheduled',
                'priority' => 'Medium',
                'customs_cleared' => false,
                'quarantine_cleared' => true,
                'documents_complete' => true,
                'weather_conditions' => 'Partly cloudy, Calm seas',
                'operation_notes' => 'Incoming from Shanghai, mixed cargo containers.',
                'special_requirements' => 'Hazmat containers need special handling'
            ],
            [
                'operation_id' => 'OP-2025-003',
                'port_id' => $ports->get(2)->id ?? $ports->first()->id,
                'operation_type' => 'Bunkering',
                'vessel_name' => 'Al Raya',
                'vessel_imo' => 'IMO9652100',
                'vessel_type' => 'Tanker',
                'vessel_size' => 85000.00,
                'vessel_flag' => 'UAE',
                'berth_number' => 'T-3',
                'berth_assignment_time' => now()->subMinutes(30),
                'scheduled_arrival' => now()->subHours(1),
                'actual_arrival' => now()->subMinutes(45),
                'scheduled_departure' => now()->addHours(6),
                'operation_start_time' => now()->subMinutes(15),
                'cargo_type' => 'Liquid Bulk',
                'cargo_volume' => 45000.00,
                'handling_equipment_used' => ['Pipelines', 'Storage Tanks'],
                'operator_name' => 'Omar Khalil',
                'pilot_required' => true,
                'pilot_name' => 'Captain Youssef Nader',
                'tugboat_required' => false,
                'handling_cost' => 8500.00,
                'port_fees' => 6200.00,
                'additional_charges' => 500.00,
                'total_cost' => 15200.00,
                'status' => 'In Progress',
                'priority' => 'Medium',
                'customs_cleared' => true,
                'quarantine_cleared' => true,
                'documents_complete' => true,
                'weather_conditions' => 'Clear, Light breeze',
                'operation_notes' => 'Fuel oil transfer operation, standard procedure.',
                'special_requirements' => 'Fire safety protocols strictly enforced'
            ],
            [
                'operation_id' => 'OP-2025-004',
                'port_id' => $ports->get(3)->id ?? $ports->first()->id,
                'operation_type' => 'Maintenance',
                'vessel_name' => 'Mediterranean Express',
                'vessel_imo' => 'IMO9543200',
                'vessel_type' => 'Ferry',
                'vessel_size' => 25000.00,
                'vessel_flag' => 'Greece',
                'berth_number' => 'M-1',
                'berth_assignment_time' => now()->addHours(3),
                'scheduled_arrival' => now()->addHours(4),
                'scheduled_departure' => now()->addHours(28),
                'cargo_type' => 'Passenger/Vehicle',
                'operator_name' => 'Fatma Abdel Rahman',
                'pilot_required' => false,
                'tugboat_required' => false,
                'handling_cost' => 3500.00,
                'port_fees' => 2800.00,
                'additional_charges' => 1500.00,
                'total_cost' => 7800.00,
                'status' => 'Scheduled',
                'priority' => 'Low',
                'customs_cleared' => true,
                'quarantine_cleared' => false,
                'documents_complete' => true,
                'weather_conditions' => 'Forecast: Clear',
                'operation_notes' => 'Scheduled maintenance of propulsion systems.',
                'special_requirements' => 'Dry dock access required, specialized technicians'
            ],
            [
                'operation_id' => 'OP-2025-005',
                'port_id' => $ports->first()->id,
                'operation_type' => 'Inspection',
                'vessel_name' => 'Nordic Star',
                'vessel_imo' => 'IMO9421800',
                'vessel_type' => 'Bulk Carrier',
                'vessel_size' => 75000.00,
                'vessel_flag' => 'Norway',
                'berth_number' => 'B-15',
                'berth_assignment_time' => now()->addMinutes(30),
                'scheduled_arrival' => now()->addHours(1),
                'scheduled_departure' => now()->addHours(8),
                'cargo_type' => 'Bulk Cargo',
                'cargo_volume' => 68000.00,
                'handling_equipment_used' => ['Bulk Loaders', 'Weighbridges'],
                'operator_name' => 'Khaled Mostafa',
                'pilot_required' => true,
                'tugboat_required' => true,
                'tugboat_count' => 1,
                'handling_cost' => 5200.00,
                'port_fees' => 4100.00,
                'additional_charges' => 300.00,
                'total_cost' => 9600.00,
                'status' => 'Waiting',
                'priority' => 'High',
                'customs_cleared' => false,
                'quarantine_cleared' => false,
                'documents_complete' => false,
                'weather_conditions' => 'Overcast, Moderate seas',
                'operation_notes' => 'Customs and quarantine inspection required before unloading.',
                'special_requirements' => 'Grain cargo requires quality inspection'
            ],
            [
                'operation_id' => 'OP-2025-006',
                'port_id' => $ports->get(1)->id ?? $ports->first()->id,
                'operation_type' => 'Loading',
                'vessel_name' => 'Ever Given',
                'vessel_imo' => 'IMO9811000',
                'vessel_type' => 'Container Ship',
                'vessel_size' => 220000.00,
                'vessel_flag' => 'Panama',
                'scheduled_arrival' => now()->addHours(6),
                'scheduled_departure' => now()->addHours(18),
                'cargo_type' => 'Container',
                'cargo_volume' => 2400.00,
                'containers_count' => 2400,
                'container_types' => ['20ft', '40ft', '40ft HC', '45ft'],
                'operator_name' => 'Hassan El-Sharif',
                'pilot_required' => true,
                'tugboat_required' => true,
                'tugboat_count' => 3,
                'handling_cost' => 18500.00,
                'port_fees' => 12000.00,
                'additional_charges' => 2500.00,
                'total_cost' => 33000.00,
                'status' => 'Scheduled',
                'priority' => 'High',
                'customs_cleared' => false,
                'quarantine_cleared' => false,
                'documents_complete' => false,
                'weather_conditions' => 'Forecast: Good conditions',
                'operation_notes' => 'Ultra Large Container Vessel, requires maximum berth capacity.',
                'special_requirements' => 'All available cranes needed, priority scheduling'
            ],
            [
                'operation_id' => 'OP-2025-007',
                'port_id' => $ports->last()->id,
                'operation_type' => 'Emergency',
                'vessel_name' => 'Rescue Unity',
                'vessel_imo' => 'IMO9234500',
                'vessel_type' => 'Naval',
                'vessel_size' => 8500.00,
                'vessel_flag' => 'Egypt',
                'berth_number' => 'E-1',
                'berth_assignment_time' => now()->subMinutes(15),
                'scheduled_arrival' => now()->subMinutes(30),
                'actual_arrival' => now()->subMinutes(20),
                'operation_start_time' => now()->subMinutes(10),
                'operator_name' => 'Captain Ahmed Farouk',
                'pilot_required' => false,
                'tugboat_required' => false,
                'handling_cost' => 0.00,
                'port_fees' => 0.00,
                'total_cost' => 0.00,
                'status' => 'In Progress',
                'priority' => 'High',
                'customs_cleared' => true,
                'quarantine_cleared' => true,
                'documents_complete' => true,
                'weather_conditions' => 'Rough seas, Strong winds',
                'operation_notes' => 'Emergency response vessel, search and rescue operation.',
                'special_requirements' => 'Immediate berth access, medical facilities on standby'
            ],
            [
                'operation_id' => 'OP-2025-008',
                'port_id' => $ports->first()->id,
                'shipment_id' => $shipments->get(2)->id ?? null,
                'operation_type' => 'Completed',
                'vessel_name' => 'Alexandria Queen',
                'vessel_imo' => 'IMO9445200',
                'vessel_type' => 'General Cargo',
                'vessel_size' => 35000.00,
                'vessel_flag' => 'Egypt',
                'berth_number' => 'B-5',
                'berth_assignment_time' => now()->subDays(1)->subHours(2),
                'scheduled_arrival' => now()->subDays(1)->subHours(3),
                'actual_arrival' => now()->subDays(1)->subHours(2)->subMinutes(30),
                'scheduled_departure' => now()->subDays(1)->addHours(6),
                'actual_departure' => now()->subDays(1)->addHours(7)->addMinutes(15),
                'operation_start_time' => now()->subDays(1)->subHours(1)->subMinutes(45),
                'operation_end_time' => now()->subDays(1)->addHours(6)->addMinutes(30),
                'cargo_type' => 'Break Bulk',
                'cargo_volume' => 8500.00,
                'handling_equipment_used' => ['Mobile Cranes', 'Forklifts'],
                'operator_name' => 'Nadia Mahmoud',
                'pilot_required' => true,
                'pilot_name' => 'Captain Sherif Hassan',
                'tugboat_required' => false,
                'handling_cost' => 4200.00,
                'port_fees' => 3100.00,
                'additional_charges' => 200.00,
                'total_cost' => 7500.00,
                'status' => 'Completed',
                'priority' => 'Medium',
                'customs_cleared' => true,
                'quarantine_cleared' => true,
                'documents_complete' => true,
                'weather_conditions' => 'Clear weather throughout operation',
                'operation_notes' => 'Smooth operation completed ahead of schedule. Steel cargo discharged without incidents.',
                'special_requirements' => 'Heavy lift cargo required specialized handling'
            ],
            [
                'operation_id' => 'OP-2025-009',
                'port_id' => $ports->get(2)->id ?? $ports->first()->id,
                'operation_type' => 'Delayed',
                'vessel_name' => 'Ocean Pioneer',
                'vessel_imo' => 'IMO9667300',
                'vessel_type' => 'Container Ship',
                'vessel_size' => 110000.00,
                'vessel_flag' => 'Marshall Islands',
                'berth_number' => 'B-10',
                'scheduled_arrival' => now()->subHours(6),
                'actual_arrival' => now()->subHours(2),
                'scheduled_departure' => now()->addHours(4),
                'cargo_type' => 'Container',
                'cargo_volume' => 1650.00,
                'containers_count' => 1650,
                'container_types' => ['20ft', '40ft'],
                'handling_equipment_used' => ['Container Cranes'],
                'operator_name' => 'Mohamed Saeed',
                'pilot_required' => true,
                'pilot_name' => 'Captain Amr Soliman',
                'tugboat_required' => true,
                'tugboat_count' => 2,
                'handling_cost' => 11200.00,
                'port_fees' => 7500.00,
                'additional_charges' => 1800.00,
                'total_cost' => 20500.00,
                'status' => 'Delayed',
                'priority' => 'Medium',
                'customs_cleared' => true,
                'quarantine_cleared' => true,
                'documents_complete' => true,
                'weather_conditions' => 'Poor visibility, Heavy rain',
                'operation_notes' => 'Vessel delayed due to adverse weather conditions in previous port.',
                'delays_reason' => 'Weather delays and congestion at previous port of call',
                'delay_duration' => 4.0,
                'special_requirements' => 'Catch up schedule, expedited handling requested'
            ],
            [
                'operation_id' => 'OP-2025-010',
                'port_id' => $ports->last()->id,
                'operation_type' => 'Transit',
                'vessel_name' => 'Suez Navigator',
                'vessel_imo' => 'IMO9578900',
                'vessel_type' => 'Bulk Carrier',
                'vessel_size' => 95000.00,
                'vessel_flag' => 'Greece',
                'scheduled_arrival' => now()->addHours(12),
                'scheduled_departure' => now()->addHours(16),
                'cargo_type' => 'Bulk Cargo',
                'cargo_volume' => 85000.00,
                'operator_name' => 'Rania El-Sherbiny',
                'pilot_required' => true,
                'tugboat_required' => false,
                'handling_cost' => 2500.00,
                'port_fees' => 1800.00,
                'additional_charges' => 300.00,
                'total_cost' => 4600.00,
                'status' => 'Scheduled',
                'priority' => 'Low',
                'customs_cleared' => false,
                'quarantine_cleared' => false,
                'documents_complete' => true,
                'weather_conditions' => 'Forecast: Fair weather',
                'operation_notes' => 'Transit passage through Suez Canal, refueling and minor supplies.',
                'special_requirements' => 'Canal transit paperwork, provisions loading'
            ]
        ];

        foreach ($operations as $operation) {
            PortOperation::create($operation);
        }

        $this->command->info('Port Operations seeder completed successfully!');
        $this->command->info('Created ' . count($operations) . ' sample port operations.');
    }
}
