<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Logistics\Port;
use App\Models\Country;

class PortSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get some countries for foreign key
        $egypt = Country::where('name', 'Egypt')->first();
        $usa = Country::where('name', 'United States')->first();
        $germany = Country::where('name', 'Germany')->first();
        $uae = Country::where('name', 'United Arab Emirates')->first();
        $china = Country::where('name', 'China')->first();
        $uk = Country::where('name', 'United Kingdom')->first();
        $singapore = Country::where('name', 'Singapore')->first();
        $netherlands = Country::where('name', 'Netherlands')->first();

        $ports = [
            [
                'name' => 'Port of Alexandria',
                'port_code' => 'EGALY',
                'port_name' => 'Port of Alexandria',
                'city' => 'Alexandria',
                'state_province' => 'Alexandria Governorate',
                'country' => 'Egypt',
                'country_id' => $egypt?->id,
                'postal_code' => '21500',
                'address' => 'Eastern Harbor, Alexandria Port Authority',
                'port_type' => 'Seaport',
                'latitude' => 31.2156,
                'longitude' => 29.9553,
                'contact_person' => 'Captain Ahmed El-Rashid',
                'contact_phone' => '+20-3-4807-6000',
                'contact_email' => 'operations@alexport.gov.eg',
                'website' => 'https://www.alexport.gov.eg',
                'operating_hours' => '24/7',
                'time_zone' => 'Africa/Cairo',
                'facilities' => [
                    'Container Handling',
                    'Bulk Cargo Handling',
                    'Break Bulk Handling',
                    'Customs Office',
                    'Port Security',
                    'Pilotage Service',
                    'Tugboat Service',
                    'Bunkering',
                    'Fresh Water Supply',
                    'Ship Repair',
                    'Cargo Inspection'
                ],
                'services' => [
                    'Stevedoring',
                    'Cargo Handling',
                    'Storage & Warehousing',
                    'Container Services',
                    'Customs Clearance',
                    'Port Agency',
                    'Ship Chandling',
                    'Bunker Supply',
                    'Technical Services'
                ],
                'max_capacity' => 1800000,
                'total_berths' => 45,
                'max_vessel_size' => 180000.00,
                'draft_depth' => 14.50,
                'major_port' => true,
                'customs_available' => true,
                'quarantine_available' => true,
                'pilotage_compulsory' => true,
                'port_authority' => 'Alexandria Port Authority',
                'handling_equipment' => [
                    'Container Cranes',
                    'Mobile Cranes',
                    'Reach Stackers',
                    'Forklifts',
                    'Terminal Tractors',
                    'Bulk Loaders',
                    'Weighbridges'
                ],
                'storage_capacity' => 500000,
                'rail_connection' => true,
                'road_connection' => true,
                'status' => 'Active'
            ],
            [
                'name' => 'Port of Suez',
                'port_code' => 'EGSUZ',

                'port_name' => 'Port of Suez',
                'city' => 'Suez',
                'state_province' => 'Suez Governorate',
                'country' => 'Egypt',
                'country_id' => $egypt?->id,
                'postal_code' => '43511',
                'address' => 'Red Sea Terminal, Suez Canal Authority',
                'port_type' => 'Seaport',
                'latitude' => 29.9668,
                'longitude' => 32.5498,
                'contact_person' => 'Captain Mahmoud Hassan',
                'contact_phone' => '+20-62-319-8888',
                'contact_email' => 'operations@suezport.gov.eg',
                'website' => 'https://www.suezport.gov.eg',
                'operating_hours' => '24/7',
                'time_zone' => 'Africa/Cairo',
                'facilities' => [
                    'Container Handling',
                    'Bulk Cargo Handling',
                    'Liquid Bulk Handling',
                    'Customs Office',
                    'Port Security',
                    'Pilotage Service',
                    'Tugboat Service',
                    'Bunkering'
                ],
                'services' => [
                    'Stevedoring',
                    'Cargo Handling',
                    'Container Services',
                    'Customs Clearance',
                    'Port Agency',
                    'Bunker Supply'
                ],
                'max_capacity' => 900000,
                'total_berths' => 28,
                'max_vessel_size' => 120000.00,
                'draft_depth' => 16.00,
                'major_port' => true,
                'customs_available' => true,
                'quarantine_available' => true,
                'pilotage_compulsory' => true,
                'port_authority' => 'Suez Canal Authority',
                'handling_equipment' => [
                    'Container Cranes',
                    'Mobile Cranes',
                    'Pipelines',
                    'Storage Tanks',
                    'Weighbridges'
                ],
                'storage_capacity' => 300000,
                'rail_connection' => true,
                'road_connection' => true,
                'status' => 'Active'
            ],
            [
                'name' => 'Cairo International Airport Cargo Terminal',
                'port_code' => 'CAILO',
                'port_name' => 'Cairo International Airport Cargo Terminal',
                'city' => 'Cairo',
                'state_province' => 'Cairo Governorate',
                'country' => 'Egypt',
                'country_id' => $egypt?->id,
                'postal_code' => '11776',
                'address' => 'Cairo International Airport, Terminal 4',
                'port_type' => 'Airport',
                'latitude' => 30.1219,
                'longitude' => 31.4056,
                'contact_person' => 'Ahmed Saleh',
                'contact_phone' => '+20-2-2265-5000',
                'contact_email' => 'cargo@cairo-airport.com',
                'website' => 'https://www.cairo-airport.com',
                'operating_hours' => '24/7',
                'time_zone' => 'Africa/Cairo',
                'facilities' => [
                    'Cold Storage',
                    'Dry Storage',
                    'Customs Office',
                    'Port Security',
                    'Cargo Inspection',
                    'Quarantine Station'
                ],
                'services' => [
                    'Cargo Handling',
                    'Storage & Warehousing',
                    'Customs Clearance',
                    'Documentation',
                    'Technical Services'
                ],
                'max_capacity' => 400000,
                'total_berths' => 8,
                'max_vessel_size' => null,
                'draft_depth' => null,
                'major_port' => true,
                'customs_available' => true,
                'quarantine_available' => true,
                'pilotage_compulsory' => false,
                'port_authority' => 'Egyptian Airports Company',
                'handling_equipment' => [
                    'Forklifts',
                    'Conveyor Systems',
                    'Weighbridges'
                ],
                'storage_capacity' => 150000,
                'rail_connection' => false,
                'road_connection' => true,
                'status' => 'Active'
            ],
            [
                'name' => 'Port of Los Angeles',
                'port_code' => 'USLAX',
                'port_name' => 'Port of Los Angeles',
                'city' => 'Los Angeles',
                'state_province' => 'California',
                'country' => 'United States',
                'country_id' => $usa?->id,
                'postal_code' => '90731',
                'address' => 'Port of Los Angeles, San Pedro Bay',
                'port_type' => 'Seaport',
                'latitude' => 33.7367,
                'longitude' => -118.2922,
                'contact_person' => 'Robert Johnson',
                'contact_phone' => '+1-310-732-3508',
                'contact_email' => 'operations@portla.org',
                'website' => 'https://www.portoflosangeles.org',
                'operating_hours' => '24/7',
                'time_zone' => 'America/Los_Angeles',
                'facilities' => [
                    'Container Handling',
                    'Bulk Cargo Handling',
                    'Break Bulk Handling',
                    'Liquid Bulk Handling',
                    'Ro-Ro Facilities',
                    'Cold Storage',
                    'Customs Office',
                    'Port Security',
                    'Ship Repair',
                    'Free Trade Zone'
                ],
                'services' => [
                    'Stevedoring',
                    'Cargo Handling',
                    'Storage & Warehousing',
                    'Container Services',
                    'Customs Clearance',
                    'Port Agency',
                    'Logistics Services',
                    'Transportation'
                ],
                'max_capacity' => 9500000,
                'total_berths' => 270,
                'max_vessel_size' => 400000.00,
                'draft_depth' => 16.50,
                'major_port' => true,
                'customs_available' => true,
                'quarantine_available' => true,
                'pilotage_compulsory' => true,
                'port_authority' => 'Port of Los Angeles',
                'handling_equipment' => [
                    'Container Cranes',
                    'Mobile Cranes',
                    'Reach Stackers',
                    'Terminal Tractors',
                    'Rail Cranes',
                    'Ship Loaders'
                ],
                'storage_capacity' => 2000000,
                'rail_connection' => true,
                'road_connection' => true,
                'status' => 'Active'
            ],
            [
                'name' => 'Port of Hamburg',
                'port_code' => 'DEHAM',
                'port_name' => 'Port of Hamburg',
                'city' => 'Hamburg',
                'state_province' => 'Hamburg',
                'country' => 'Germany',
                'country_id' => $germany?->id,
                'postal_code' => '20457',
                'address' => 'Neuer Wandrahm 4, HafenCity',
                'port_type' => 'Seaport',
                'latitude' => 53.5439,
                'longitude' => 9.9678,
                'contact_person' => 'Klaus Weber',
                'contact_phone' => '+49-40-3703-0',
                'contact_email' => 'info@hafen-hamburg.de',
                'website' => 'https://www.hafen-hamburg.de',
                'operating_hours' => '24/7',
                'time_zone' => 'Europe/Berlin',
                'facilities' => [
                    'Container Handling',
                    'Bulk Cargo Handling',
                    'Break Bulk Handling',
                    'Cold Storage',
                    'Customs Office',
                    'Port Security',
                    'Ship Repair',
                    'Free Trade Zone'
                ],
                'services' => [
                    'Stevedoring',
                    'Cargo Handling',
                    'Storage & Warehousing',
                    'Container Services',
                    'Customs Clearance',
                    'Logistics Services'
                ],
                'max_capacity' => 8800000,
                'total_berths' => 320,
                'max_vessel_size' => 380000.00,
                'draft_depth' => 15.10,
                'major_port' => true,
                'customs_available' => true,
                'quarantine_available' => true,
                'pilotage_compulsory' => true,
                'port_authority' => 'Hamburg Port Authority',
                'handling_equipment' => [
                    'Container Cranes',
                    'Mobile Cranes',
                    'Reach Stackers',
                    'Rail Cranes',
                    'Conveyor Systems'
                ],
                'storage_capacity' => 1500000,
                'rail_connection' => true,
                'road_connection' => true,
                'status' => 'Active'
            ],
            [
                'name' => 'Jebel Ali Port',
                'port_code' => 'AEJEA',
                'port_name' => 'Jebel Ali Port',
                'city' => 'Dubai',
                'state_province' => 'Dubai',
                'country' => 'United Arab Emirates',
                'country_id' => $uae?->id,
                'postal_code' => '17000',
                'address' => 'Jebel Ali Free Zone Authority',
                'port_type' => 'Seaport',
                'latitude' => 25.0124,
                'longitude' => 55.1003,
                'contact_person' => 'Omar Al-Rashid',
                'contact_phone' => '+971-4-881-5555',
                'contact_email' => 'operations@jafza.ae',
                'website' => 'https://www.dpworld.com/jebel-ali',
                'operating_hours' => '24/7',
                'time_zone' => 'Asia/Dubai',
                'facilities' => [
                    'Container Handling',
                    'Bulk Cargo Handling',
                    'Break Bulk Handling',
                    'Customs Office',
                    'Port Security',
                    'Ship Repair',
                    'Free Trade Zone'
                ],
                'services' => [
                    'Stevedoring',
                    'Cargo Handling',
                    'Storage & Warehousing',
                    'Container Services',
                    'Customs Clearance',
                    'Logistics Services'
                ],
                'max_capacity' => 15000000,
                'total_berths' => 67,
                'max_vessel_size' => 400000.00,
                'draft_depth' => 17.00,
                'major_port' => true,
                'customs_available' => true,
                'quarantine_available' => true,
                'pilotage_compulsory' => true,
                'port_authority' => 'DP World',
                'handling_equipment' => [
                    'Container Cranes',
                    'Mobile Cranes',
                    'Reach Stackers',
                    'Terminal Tractors'
                ],
                'storage_capacity' => 3000000,
                'rail_connection' => false,
                'road_connection' => true,
                'status' => 'Active'
            ],
            [
                'name' => 'Port of Shanghai',
                'port_code' => 'CNSHA',
                'port_name' => 'Port of Shanghai',
                'city' => 'Shanghai',
                'state_province' => 'Shanghai',
                'country' => 'China',
                'country_id' => $china?->id,
                'postal_code' => '200135',
                'address' => 'Yangshan Deep Water Port',
                'port_type' => 'Seaport',
                'latitude' => 31.2304,
                'longitude' => 121.4737,
                'contact_person' => 'Li Wei',
                'contact_phone' => '+86-21-5080-5555',
                'contact_email' => 'info@portshanghai.com.cn',
                'website' => 'https://www.portshanghai.com.cn',
                'operating_hours' => '24/7',
                'time_zone' => 'Asia/Shanghai',
                'facilities' => [
                    'Container Handling',
                    'Bulk Cargo Handling',
                    'Break Bulk Handling',
                    'Liquid Bulk Handling',
                    'Cold Storage',
                    'Customs Office',
                    'Port Security'
                ],
                'services' => [
                    'Stevedoring',
                    'Cargo Handling',
                    'Storage & Warehousing',
                    'Container Services',
                    'Customs Clearance'
                ],
                'max_capacity' => 47000000,
                'total_berths' => 125,
                'max_vessel_size' => 400000.00,
                'draft_depth' => 16.50,
                'major_port' => true,
                'customs_available' => true,
                'quarantine_available' => true,
                'pilotage_compulsory' => true,
                'port_authority' => 'Shanghai International Port Group',
                'handling_equipment' => [
                    'Container Cranes',
                    'Mobile Cranes',
                    'Reach Stackers',
                    'Terminal Tractors',
                    'Rail Cranes'
                ],
                'storage_capacity' => 8000000,
                'rail_connection' => true,
                'road_connection' => true,
                'status' => 'Active'
            ],
            [
                'name' => 'London Gateway Port',
                'port_code' => 'GBLGW',
                'port_name' => 'London Gateway Port',
                'city' => 'London',
                'state_province' => 'England',
                'country' => 'United Kingdom',
                'country_id' => $uk?->id,
                'postal_code' => 'SS17 9DX',
                'address' => 'London Gateway, Stanford-le-Hope, Essex',
                'port_type' => 'Container Terminal',
                'latitude' => 51.4700,
                'longitude' => -0.4543,
                'contact_person' => 'James Smith',
                'contact_phone' => '+44-1375-648-000',
                'contact_email' => 'operations@londongateway.com',
                'website' => 'https://www.londongateway.com',
                'operating_hours' => '24/7',
                'time_zone' => 'Europe/London',
                'facilities' => [
                    'Container Handling',
                    'Cold Storage',
                    'Customs Office',
                    'Port Security',
                    'Rail Connection'
                ],
                'services' => [
                    'Container Services',
                    'Storage & Warehousing',
                    'Customs Clearance',
                    'Logistics Services'
                ],
                'max_capacity' => 3600000,
                'total_berths' => 6,
                'max_vessel_size' => 400000.00,
                'draft_depth' => 16.00,
                'major_port' => true,
                'customs_available' => true,
                'quarantine_available' => false,
                'pilotage_compulsory' => true,
                'port_authority' => 'DP World London Gateway',
                'handling_equipment' => [
                    'Container Cranes',
                    'Terminal Tractors',
                    'Rail Cranes'
                ],
                'storage_capacity' => 800000,
                'rail_connection' => true,
                'road_connection' => true,
                'status' => 'Active'
            ],
            [
                'name' => 'Port of Singapore',
                'port_code' => 'SGSIN',
                'port_name' => 'Port of Singapore',
                'city' => 'Singapore',
                'state_province' => null,
                'country' => 'Singapore',
                'country_id' => $singapore?->id,
                'postal_code' => '099253',
                'address' => 'Tanjong Pagar Terminal',
                'port_type' => 'Seaport',
                'latitude' => 1.2644,
                'longitude' => 103.8076,
                'contact_person' => 'Tan Wei Ming',
                'contact_phone' => '+65-6275-2000',
                'contact_email' => 'operations@psa.com.sg',
                'website' => 'https://www.singaporepsa.com',
                'operating_hours' => '24/7',
                'time_zone' => 'Asia/Singapore',
                'facilities' => [
                    'Container Handling',
                    'Bulk Cargo Handling',
                    'Break Bulk Handling',
                    'Liquid Bulk Handling',
                    'Bunkering',
                    'Ship Repair',
                    'Free Trade Zone'
                ],
                'services' => [
                    'Stevedoring',
                    'Cargo Handling',
                    'Storage & Warehousing',
                    'Container Services',
                    'Bunker Supply',
                    'Ship Chandling'
                ],
                'max_capacity' => 37200000,
                'total_berths' => 200,
                'max_vessel_size' => 400000.00,
                'draft_depth' => 16.00,
                'major_port' => true,
                'customs_available' => true,
                'quarantine_available' => true,
                'pilotage_compulsory' => true,
                'port_authority' => 'Maritime and Port Authority of Singapore',
                'handling_equipment' => [
                    'Container Cranes',
                    'Mobile Cranes',
                    'Reach Stackers',
                    'Terminal Tractors'
                ],
                'storage_capacity' => 5000000,
                'rail_connection' => false,
                'road_connection' => true,
                'status' => 'Active'
            ],
            [
                'name' => 'Port of Rotterdam',
                'port_code' => 'NLRTM',
                'port_name' => 'Port of Rotterdam',
                'city' => 'Rotterdam',
                'state_province' => 'South Holland',
                'country' => 'Netherlands',
                'country_id' => $netherlands?->id,
                'postal_code' => '3011 AD',
                'address' => 'Wilhelminakade 909',
                'port_type' => 'Seaport',
                'latitude' => 51.9225,
                'longitude' => 4.4792,
                'contact_person' => 'Pieter Van Der Berg',
                'contact_phone' => '+31-10-252-1010',
                'contact_email' => 'info@portofrotterdam.com',
                'website' => 'https://www.portofrotterdam.com',
                'operating_hours' => '24/7',
                'time_zone' => 'Europe/Amsterdam',
                'facilities' => [
                    'Container Handling',
                    'Bulk Cargo Handling',
                    'Break Bulk Handling',
                    'Liquid Bulk Handling',
                    'Cold Storage',
                    'Ship Repair'
                ],
                'services' => [
                    'Stevedoring',
                    'Cargo Handling',
                    'Storage & Warehousing',
                    'Customs Clearance',
                    'Logistics Services'
                ],
                'max_capacity' => 15300000,
                'total_berths' => 180,
                'max_vessel_size' => 400000.00,
                'draft_depth' => 24.00,
                'major_port' => true,
                'customs_available' => true,
                'quarantine_available' => true,
                'pilotage_compulsory' => true,
                'port_authority' => 'Port of Rotterdam Authority',
                'handling_equipment' => [
                    'Container Cranes',
                    'Mobile Cranes',
                    'Pipelines',
                    'Storage Tanks',
                    'Rail Cranes'
                ],
                'storage_capacity' => 3500000,
                'rail_connection' => true,
                'road_connection' => true,
                'status' => 'Active'
            ],
            [
                'name' => 'Port Said East Port',
                'port_code' => 'EGPOR',
                'port_name' => 'Port Said East Port',
                'city' => 'Port Said',
                'state_province' => 'Port Said Governorate',
                'country' => 'Egypt',
                'country_id' => $egypt?->id,
                'postal_code' => '42511',
                'address' => 'East Port Said, Suez Canal Economic Zone',
                'port_type' => 'Container Terminal',
                'latitude' => 31.2653,
                'longitude' => 32.3019,
                'contact_person' => 'Samir Farid',
                'contact_phone' => '+20-66-333-4444',
                'contact_email' => 'operations@eastportsaid.com',
                'website' => 'https://www.eastportsaid.com',
                'operating_hours' => '24/7',
                'time_zone' => 'Africa/Cairo',
                'facilities' => [
                    'Container Handling',
                    'Customs Office',
                    'Port Security',
                    'Free Trade Zone'
                ],
                'services' => [
                    'Container Services',
                    'Storage & Warehousing',
                    'Customs Clearance',
                    'Logistics Services'
                ],
                'max_capacity' => 3200000,
                'total_berths' => 18,
                'max_vessel_size' => 220000.00,
                'draft_depth' => 18.00,
                'major_port' => true,
                'customs_available' => true,
                'quarantine_available' => true,
                'pilotage_compulsory' => true,
                'port_authority' => 'Suez Canal Economic Zone Authority',
                'handling_equipment' => [
                    'Container Cranes',
                    'Reach Stackers',
                    'Terminal Tractors'
                ],
                'storage_capacity' => 650000,
                'rail_connection' => false,
                'road_connection' => true,
                'status' => 'Active'
            ],
            [
                'name' => 'Test Inactive Port',
                'port_code' => 'TESTP',
                'port_name' => 'Test Inactive Port',
                'city' => 'Test City',
                'country' => 'Egypt',
                'country_id' => $egypt?->id,
                'address' => 'Test Address for Inactive Port',
                'port_type' => 'Dry Port',
                'contact_person' => 'Test Person',
                'contact_phone' => '+20-2-000-0000',
                'contact_email' => 'test@inactive.com',
                'operating_hours' => 'Closed',
                'facilities' => ['Dry Storage'],
                'services' => ['Storage & Warehousing'],
                'major_port' => false,
                'customs_available' => false,
                'quarantine_available' => false,
                'pilotage_compulsory' => false,
                'rail_connection' => false,
                'road_connection' => true,
                'status' => 'Inactive'
            ]
        ];

        foreach ($ports as $port) {
            Port::create($port);
        }

        $this->command->info('Port seeder completed successfully!');
    }
}
