<?php

namespace Database\Seeders;

use App\Models\Port;
use Illuminate\Database\Seeder;

class PortSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $ports = [
            // Major Middle Eastern Ports
            [
                'port_code' => 'AEJEA',
                'port_name' => 'Jebel Ali Port',
                'port_type' => 'Container Terminal',
                'country' => 'United Arab Emirates',
                'city' => 'Dubai',
                'state_province' => 'Dubai',
                'latitude' => 25.0025,
                'longitude' => 55.1147,
                'time_zone' => 'Asia/Dubai',
                'port_authority' => 'DP World',
                'contact_email' => 'info@jebelali.dpworld.ae',
                'contact_phone' => '+971-4-881-5000',
                'website' => 'https://www.dpworld.com',
                'facilities' => ['Container Terminal', 'Free Zone', 'Warehouses', 'Ship Repair'],
                'services' => ['Container Handling', 'Customs Clearance', 'Cargo Storage', 'Ship Services'],
                'terminal_operators' => ['DP World', 'Jebel Ali Free Zone Authority'],
                'max_vessel_size' => '400m LOA',
                'max_draft_meters' => 16.0,
                'berth_count' => 80,
                'storage_capacity' => 19300000.0,
                'crane_capacity' => 65.0,
                'working_hours' => ['24/7 Operations'],
                'operational_status' => 'Fully Operational',
                'customs_available' => true,
                'quarantine_available' => true,
                'bunker_available' => true,
                'fresh_water_available' => true,
                'rail_connection' => true,
                'road_connection' => true,
                'airport_distance_km' => 35.0,
                'port_charges' => ['Container Handling' => 150, 'Storage' => 50, 'Security' => 25],
                'pilot_required' => true,
                'tugs_available' => true,
                'anchorage_available' => true,
                'security_level' => 'ISPS Level 1',
                'is_major_port' => true,
                'is_container_port' => true,
                'is_bulk_port' => false,
                'is_cruise_port' => false,
                'handling_equipment' => ['Container Cranes', 'RTG Cranes', 'Reach Stackers', 'Terminal Tractors'],
                'cargo_types_handled' => ['Containers', 'General Cargo', 'Automotive', 'Project Cargo'],
                'restrictions' => ['Dangerous Goods Restricted Areas', 'Maximum Container Height 9.6m'],
                'weather_conditions' => ['Operational Year Round', 'Sandstorm Delays Possible'],
                'annual_throughput' => 15300000.0,
                'established_year' => 2004,
                'is_active' => true,
                'sort_order' => 1,
                'notes' => 'Worlds largest man-made port and leading container hub in Middle East'
            ],
            [
                'port_code' => 'EGALY',
                'port_name' => 'Port of Alexandria',
                'port_type' => 'Multi-Purpose',
                'country' => 'Egypt',
                'city' => 'Alexandria',
                'state_province' => 'Alexandria',
                'latitude' => 31.2001,
                'longitude' => 29.9187,
                'time_zone' => 'Africa/Cairo',
                'port_authority' => 'Alexandria Port Authority',
                'contact_email' => 'info@apaegypt.gov.eg',
                'contact_phone' => '+20-3-480-0000',
                'website' => 'http://www.apaegypt.gov.eg',
                'facilities' => ['Container Terminal', 'General Cargo Berths', 'Grain Silos', 'Oil Terminal'],
                'services' => ['Container Handling', 'Bulk Handling', 'Customs', 'Ship Repair'],
                'terminal_operators' => ['Alexandria Container & Cargo Handling Company', 'APM Terminals'],
                'max_vessel_size' => '350m LOA',
                'max_draft_meters' => 14.0,
                'berth_count' => 45,
                'storage_capacity' => 2500000.0,
                'crane_capacity' => 40.0,
                'working_hours' => ['06:00-22:00 Mon-Sat', 'Emergency 24/7'],
                'operational_status' => 'Fully Operational',
                'customs_available' => true,
                'quarantine_available' => true,
                'bunker_available' => true,
                'fresh_water_available' => true,
                'rail_connection' => true,
                'road_connection' => true,
                'airport_distance_km' => 45.0,
                'port_charges' => ['Container Handling' => 120, 'Storage' => 40, 'Pilot' => 300],
                'pilot_required' => true,
                'tugs_available' => true,
                'anchorage_available' => true,
                'security_level' => 'ISPS Level 1',
                'is_major_port' => true,
                'is_container_port' => true,
                'is_bulk_port' => true,
                'is_cruise_port' => true,
                'handling_equipment' => ['Container Cranes', 'Mobile Cranes', 'Conveyor Systems', 'Forklifts'],
                'cargo_types_handled' => ['Containers', 'General Cargo', 'Bulk', 'Liquid Bulk', 'Passengers'],
                'restrictions' => ['Draft Limitation 14m', 'Length Restriction for Some Berths'],
                'weather_conditions' => ['Winter Storm Delays', 'Summer Heat Operations'],
                'annual_throughput' => 1800000.0,
                'established_year' => 2000,
                'is_active' => true,
                'sort_order' => 2,
                'notes' => 'Egypts main Mediterranean port with rich historical significance'
            ],
            [
                'port_code' => 'SAJAR',
                'port_name' => 'King Abdulaziz Port',
                'port_type' => 'Container Terminal',
                'country' => 'Saudi Arabia',
                'city' => 'Dammam',
                'state_province' => 'Eastern Province',
                'latitude' => 26.3927,
                'longitude' => 50.1059,
                'time_zone' => 'Asia/Riyadh',
                'port_authority' => 'Saudi Ports Authority',
                'contact_email' => 'info@ports.gov.sa',
                'contact_phone' => '+966-13-857-0000',
                'website' => 'https://www.ports.gov.sa',
                'facilities' => ['Container Terminal', 'General Cargo', 'Ro-Ro Terminal', 'Passenger Terminal'],
                'services' => ['Container Handling', 'Vehicle Processing', 'Customs', 'Warehousing'],
                'terminal_operators' => ['Saudi Ports Authority', 'Red Sea Gateway Terminal'],
                'max_vessel_size' => '300m LOA',
                'max_draft_meters' => 12.5,
                'berth_count' => 35,
                'storage_capacity' => 1800000.0,
                'crane_capacity' => 50.0,
                'working_hours' => ['24/7 Container Operations', 'General Cargo 06:00-20:00'],
                'operational_status' => 'Fully Operational',
                'customs_available' => true,
                'quarantine_available' => true,
                'bunker_available' => true,
                'fresh_water_available' => true,
                'rail_connection' => true,
                'road_connection' => true,
                'airport_distance_km' => 50.0,
                'port_charges' => ['Container Handling' => 140, 'Vehicle Handling' => 200, 'Storage' => 45],
                'pilot_required' => true,
                'tugs_available' => true,
                'anchorage_available' => true,
                'security_level' => 'ISPS Level 1',
                'is_major_port' => true,
                'is_container_port' => true,
                'is_bulk_port' => false,
                'is_cruise_port' => false,
                'handling_equipment' => ['STS Cranes', 'RTG Cranes', 'Mobile Cranes', 'Car Carriers'],
                'cargo_types_handled' => ['Containers', 'Vehicles', 'General Cargo', 'Project Cargo'],
                'restrictions' => ['Dangerous Goods Special Handling', 'Vehicle Import Inspection Required'],
                'weather_conditions' => ['High Temperature Summer', 'Sandstorm Delays'],
                'annual_throughput' => 1200000.0,
                'established_year' => 2006,
                'is_active' => true,
                'sort_order' => 3,
                'notes' => 'Major gateway for vehicle imports and containers in Saudi Arabia'
            ],
            [
                'port_code' => 'LBBEY',
                'port_name' => 'Port of Beirut',
                'port_type' => 'Multi-Purpose',
                'country' => 'Lebanon',
                'city' => 'Beirut',
                'state_province' => 'Beirut',
                'latitude' => 33.9016,
                'longitude' => 35.5106,
                'time_zone' => 'Asia/Beirut',
                'port_authority' => 'Port of Beirut Authority',
                'contact_email' => 'info@portofbeirut.com',
                'contact_phone' => '+961-1-580-380',
                'website' => 'http://www.portofbeirut.com',
                'facilities' => ['Container Terminal', 'General Cargo', 'Grain Terminal', 'Free Zone'],
                'services' => ['Container Handling', 'Customs', 'Warehousing', 'Transshipment'],
                'terminal_operators' => ['Beirut Container Terminal Consortium'],
                'max_vessel_size' => '280m LOA',
                'max_draft_meters' => 11.0,
                'berth_count' => 16,
                'storage_capacity' => 800000.0,
                'crane_capacity' => 35.0,
                'working_hours' => ['07:00-19:00 Mon-Fri', '07:00-13:00 Saturday'],
                'operational_status' => 'Limited Operations',
                'customs_available' => true,
                'quarantine_available' => true,
                'bunker_available' => false,
                'fresh_water_available' => true,
                'rail_connection' => false,
                'road_connection' => true,
                'airport_distance_km' => 8.0,
                'port_charges' => ['Container Handling' => 110, 'Storage' => 35, 'Documentation' => 50],
                'pilot_required' => true,
                'tugs_available' => true,
                'anchorage_available' => true,
                'security_level' => 'ISPS Level 2',
                'is_major_port' => false,
                'is_container_port' => true,
                'is_bulk_port' => false,
                'is_cruise_port' => false,
                'handling_equipment' => ['Container Cranes', 'Mobile Cranes', 'Forklifts', 'Terminal Tractors'],
                'cargo_types_handled' => ['Containers', 'General Cargo', 'Bulk Commodities'],
                'restrictions' => ['Security Restrictions', 'Limited Night Operations'],
                'weather_conditions' => ['Mediterranean Climate', 'Winter Storm Delays'],
                'annual_throughput' => 900000.0,
                'established_year' => 2009,
                'is_active' => true,
                'sort_order' => 4,
                'notes' => 'Historic Mediterranean port serving Lebanon and transit trade'
            ],
            [
                'port_code' => 'KWKWI',
                'port_name' => 'Shuwaikh Port',
                'port_type' => 'Multi-Purpose',
                'country' => 'Kuwait',
                'city' => 'Kuwait City',
                'state_province' => 'Kuwait',
                'latitude' => 29.3375,
                'longitude' => 47.9187,
                'time_zone' => 'Asia/Kuwait',
                'port_authority' => 'Kuwait Ports Authority',
                'contact_email' => 'info@kpa.gov.kw',
                'contact_phone' => '+965-2481-8900',
                'website' => 'http://www.kpa.gov.kw',
                'facilities' => ['Container Terminal', 'General Cargo', 'Oil Terminal', 'Fishing Harbor'],
                'services' => ['Container Handling', 'Oil Services', 'Customs', 'Ship Repair'],
                'terminal_operators' => ['Kuwait Ports Authority', 'Agility Logistics'],
                'max_vessel_size' => '250m LOA',
                'max_draft_meters' => 10.0,
                'berth_count' => 21,
                'storage_capacity' => 600000.0,
                'crane_capacity' => 30.0,
                'working_hours' => ['06:00-22:00 Daily', '24/7 Oil Operations'],
                'operational_status' => 'Fully Operational',
                'customs_available' => true,
                'quarantine_available' => true,
                'bunker_available' => true,
                'fresh_water_available' => true,
                'rail_connection' => false,
                'road_connection' => true,
                'airport_distance_km' => 20.0,
                'port_charges' => ['Container Handling' => 130, 'Storage' => 40, 'Oil Services' => 500],
                'pilot_required' => true,
                'tugs_available' => true,
                'anchorage_available' => true,
                'security_level' => 'ISPS Level 1',
                'is_major_port' => false,
                'is_container_port' => true,
                'is_bulk_port' => true,
                'is_cruise_port' => false,
                'handling_equipment' => ['Mobile Cranes', 'Forklifts', 'Oil Pumps', 'Terminal Tractors'],
                'cargo_types_handled' => ['Containers', 'General Cargo', 'Oil Products', 'Food Items'],
                'restrictions' => ['Tidal Restrictions', 'Oil Cargo Special Requirements'],
                'weather_conditions' => ['Extreme Summer Heat', 'Shamal Wind Delays'],
                'annual_throughput' => 750000.0,
                'established_year' => 2011,
                'is_active' => true,
                'sort_order' => 5,
                'notes' => 'Kuwaits main commercial port handling diverse cargo types'
            ],
            [
                'port_code' => 'QADOH',
                'port_name' => 'Hamad Port',
                'port_type' => 'Container Terminal',
                'country' => 'Qatar',
                'city' => 'Doha',
                'state_province' => 'Doha',
                'latitude' => 25.1473,
                'longitude' => 51.6348,
                'time_zone' => 'Asia/Qatar',
                'port_authority' => 'Mwani Qatar',
                'contact_email' => 'info@mwani.com.qa',
                'contact_phone' => '+974-4013-3333',
                'website' => 'https://www.mwani.com.qa',
                'facilities' => ['Container Terminal', 'General Cargo', 'Automotive Terminal', 'Logistics Zone'],
                'services' => ['Container Handling', 'Vehicle Processing', 'Customs', 'Logistics Services'],
                'terminal_operators' => ['QTerminals', 'Milaha'],
                'max_vessel_size' => '400m LOA',
                'max_draft_meters' => 18.0,
                'berth_count' => 25,
                'storage_capacity' => 6000000.0,
                'crane_capacity' => 70.0,
                'working_hours' => ['24/7 Operations'],
                'operational_status' => 'Fully Operational',
                'customs_available' => true,
                'quarantine_available' => true,
                'bunker_available' => true,
                'fresh_water_available' => true,
                'rail_connection' => false,
                'road_connection' => true,
                'airport_distance_km' => 15.0,
                'port_charges' => ['Container Handling' => 155, 'Storage' => 55, 'Automotive' => 180],
                'pilot_required' => true,
                'tugs_available' => true,
                'anchorage_available' => true,
                'security_level' => 'ISPS Level 1',
                'is_major_port' => true,
                'is_container_port' => true,
                'is_bulk_port' => false,
                'is_cruise_port' => false,
                'handling_equipment' => ['Super Post Panamax Cranes', 'E-RTG Cranes', 'AGV Systems', 'RoRo Equipment'],
                'cargo_types_handled' => ['Containers', 'Vehicles', 'General Cargo', 'Project Cargo'],
                'restrictions' => ['High Security Zone', 'Automated Terminal Areas'],
                'weather_conditions' => ['Hot Summer Operations', 'Sandstorm Delays Possible'],
                'annual_throughput' => 2000000.0,
                'established_year' => 2017,
                'is_active' => true,
                'sort_order' => 6,
                'notes' => 'State-of-the-art automated port serving Qatar and regional trade'
            ]
        ];

        foreach ($ports as $portData) {
            Port::create(array_merge($portData, []));
        }
    }
}
