<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\QuantityType;

class QuantityTypeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $quantityTypes = [
            // Container Units - Most Common in Logistics
            [
                'quantity_code' => 'TEU',
                'quantity_name' => 'Twenty-foot Equivalent Unit',
                'quantity_category' => 'Container',
                'unit_of_measure' => 'Container',
                'unit_symbol' => 'TEU',
                'base_unit' => 'TEU',
                'conversion_factor' => 1.0,
                'decimal_places' => 0,
                'description' => 'Standard 20-foot container equivalent unit measurement - primary container measurement in shipping',
                'calculation_method' => 'Count of 20ft container equivalents',
                'applicable_cargo_types' => ['Containers', 'General Cargo', 'FCL'],
                'industry_standards' => ['ISO 668', 'CSC Convention'],
                'common_ranges' => ['min' => 1, 'max' => 50000],
                'validation_rules' => ['positive_integer'],
                'display_format' => '%.0f TEU',
                'reporting_category' => 'Container Volume',
                'is_weight_based' => false,
                'is_volume_based' => true,
                'is_count_based' => true,
                'is_dimension_based' => false,
                'allows_fractions' => false,
                'requires_dimensions' => false,
                'auto_calculate' => false,
                'is_billable' => true,
                'billing_multiplier' => 1.0,
                'minimum_chargeable' => 1.0,
                'rounding_method' => 'up',
                'is_standard' => true,
                'is_active' => true,
                'sort_order' => 1,
                'notes' => 'Primary container measurement unit in shipping industry'
            ],
            [
                'quantity_code' => 'FEU',
                'quantity_name' => 'Forty-foot Equivalent Unit',
                'quantity_category' => 'Container',
                'unit_of_measure' => 'Container',
                'unit_symbol' => 'FEU',
                'base_unit' => 'TEU',
                'conversion_factor' => 2.0,
                'decimal_places' => 0,
                'description' => 'Standard 40-foot container unit equals 2 TEU',
                'calculation_method' => 'Count of 40ft containers',
                'applicable_cargo_types' => ['Containers', 'General Cargo', 'FCL'],
                'industry_standards' => ['ISO 668', 'CSC Convention'],
                'common_ranges' => ['min' => 1, 'max' => 25000],
                'validation_rules' => ['positive_integer'],
                'display_format' => '%.0f FEU',
                'reporting_category' => 'Container Volume',
                'is_weight_based' => false,
                'is_volume_based' => true,
                'is_count_based' => true,
                'is_dimension_based' => false,
                'allows_fractions' => false,
                'requires_dimensions' => false,
                'auto_calculate' => false,
                'is_billable' => true,
                'billing_multiplier' => 2.0,
                'minimum_chargeable' => 1.0,
                'rounding_method' => 'up',
                'is_standard' => true,
                'is_active' => true,
                'sort_order' => 2,
                'notes' => '40-foot container standard measurement'
            ],

            // Weight Measurements - Essential for All Cargo
            [
                'quantity_code' => 'KG',
                'quantity_name' => 'Kilogram',
                'quantity_category' => 'Weight',
                'unit_of_measure' => 'Kilogram',
                'unit_symbol' => 'kg',
                'base_unit' => 'kg',
                'conversion_factor' => 1.0,
                'decimal_places' => 3,
                'description' => 'Metric unit of mass measurement - standard weight unit',
                'calculation_method' => 'Direct weight measurement using scales',
                'applicable_cargo_types' => ['General Cargo', 'Bulk', 'Containers', 'Break Bulk', 'LCL'],
                'industry_standards' => ['SI Units', 'ISO 80000-4'],
                'common_ranges' => ['min' => 0.001, 'max' => 100000000],
                'validation_rules' => ['positive_number'],
                'display_format' => '%.3f kg',
                'reporting_category' => 'Gross Weight',
                'is_weight_based' => true,
                'is_volume_based' => false,
                'is_count_based' => false,
                'is_dimension_based' => false,
                'allows_fractions' => true,
                'requires_dimensions' => false,
                'auto_calculate' => false,
                'is_billable' => true,
                'billing_multiplier' => 1.0,
                'minimum_chargeable' => 0.001,
                'rounding_method' => 'nearest',
                'is_standard' => true,
                'is_active' => true,
                'sort_order' => 3,
                'notes' => 'Standard metric weight unit for all cargo types'
            ],
            [
                'quantity_code' => 'MT',
                'quantity_name' => 'Metric Ton',
                'quantity_category' => 'Weight',
                'unit_of_measure' => 'Metric Ton',
                'unit_symbol' => 'MT',
                'base_unit' => 'kg',
                'conversion_factor' => 1000.0,
                'decimal_places' => 3,
                'description' => 'Metric ton (1000 kg) for large cargo weights',
                'calculation_method' => 'Weight in thousands of kilograms',
                'applicable_cargo_types' => ['Bulk', 'Heavy Cargo', 'Break Bulk', 'Project Cargo'],
                'industry_standards' => ['SI Units', 'ISO 80000-4'],
                'common_ranges' => ['min' => 0.001, 'max' => 100000],
                'validation_rules' => ['positive_number'],
                'display_format' => '%.3f MT',
                'reporting_category' => 'Gross Weight',
                'is_weight_based' => true,
                'is_volume_based' => false,
                'is_count_based' => false,
                'is_dimension_based' => false,
                'allows_fractions' => true,
                'requires_dimensions' => false,
                'auto_calculate' => false,
                'is_billable' => true,
                'billing_multiplier' => 1.0,
                'minimum_chargeable' => 0.001,
                'rounding_method' => 'nearest',
                'is_standard' => true,
                'is_active' => true,
                'sort_order' => 4,
                'notes' => 'Used for heavy cargo and bulk commodities'
            ],

            // Volume Measurements - Critical for Space Planning
            [
                'quantity_code' => 'CBM',
                'quantity_name' => 'Cubic Meter',
                'quantity_category' => 'Volume',
                'unit_of_measure' => 'Cubic Meter',
                'unit_symbol' => 'm³',
                'base_unit' => 'cbm',
                'conversion_factor' => 1.0,
                'decimal_places' => 3,
                'description' => 'Standard volume measurement in cubic meters',
                'calculation_method' => 'Length × Width × Height in meters',
                'applicable_cargo_types' => ['General Cargo', 'Break Bulk', 'LCL'],
                'industry_standards' => ['SI Units', 'ISO 80000-3'],
                'common_ranges' => ['min' => 0.001, 'max' => 50000],
                'validation_rules' => ['positive_number'],
                'display_format' => '%.3f m³',
                'reporting_category' => 'Volume',
                'is_weight_based' => false,
                'is_volume_based' => true,
                'is_count_based' => false,
                'is_dimension_based' => true,
                'allows_fractions' => true,
                'requires_dimensions' => true,
                'auto_calculate' => true,
                'is_billable' => true,
                'billing_multiplier' => 1.0,
                'minimum_chargeable' => 0.001,
                'rounding_method' => 'up',
                'is_standard' => true,
                'is_active' => true,
                'sort_order' => 5,
                'notes' => 'Standard volumetric measurement for LCL and break bulk'
            ],
            [
                'quantity_code' => 'CFT',
                'quantity_name' => 'Cubic Feet',
                'quantity_category' => 'Volume',
                'unit_of_measure' => 'Cubic Feet',
                'unit_symbol' => 'ft³',
                'base_unit' => 'cbm',
                'conversion_factor' => 0.0283168,
                'decimal_places' => 2,
                'description' => 'Imperial volume measurement in cubic feet',
                'calculation_method' => 'Length × Width × Height in feet',
                'applicable_cargo_types' => ['General Cargo', 'Break Bulk', 'Air Cargo'],
                'industry_standards' => ['Imperial Units'],
                'common_ranges' => ['min' => 0.1, 'max' => 100000],
                'validation_rules' => ['positive_number'],
                'display_format' => '%.2f ft³',
                'reporting_category' => 'Volume',
                'is_weight_based' => false,
                'is_volume_based' => true,
                'is_count_based' => false,
                'is_dimension_based' => true,
                'allows_fractions' => true,
                'requires_dimensions' => true,
                'auto_calculate' => true,
                'is_billable' => true,
                'billing_multiplier' => 1.0,
                'minimum_chargeable' => 0.1,
                'rounding_method' => 'up',
                'is_standard' => false,
                'is_active' => true,
                'sort_order' => 6,
                'notes' => 'Imperial volume unit commonly used in North America'
            ],

            // Count/Piece Measurements
            [
                'quantity_code' => 'PCS',
                'quantity_name' => 'Pieces',
                'quantity_category' => 'Count',
                'unit_of_measure' => 'Pieces',
                'unit_symbol' => 'pcs',
                'base_unit' => 'pieces',
                'conversion_factor' => 1.0,
                'decimal_places' => 0,
                'description' => 'Individual item count',
                'calculation_method' => 'Physical count of individual items',
                'applicable_cargo_types' => ['General Cargo', 'Break Bulk', 'Project Cargo'],
                'industry_standards' => ['Universal'],
                'common_ranges' => ['min' => 1, 'max' => 1000000],
                'validation_rules' => ['positive_integer'],
                'display_format' => '%.0f pcs',
                'reporting_category' => 'Item Count',
                'is_weight_based' => false,
                'is_volume_based' => false,
                'is_count_based' => true,
                'is_dimension_based' => false,
                'allows_fractions' => false,
                'requires_dimensions' => false,
                'auto_calculate' => false,
                'is_billable' => true,
                'billing_multiplier' => 1.0,
                'minimum_chargeable' => 1.0,
                'rounding_method' => 'up',
                'is_standard' => true,
                'is_active' => true,
                'sort_order' => 7,
                'notes' => 'Basic unit count for individual items'
            ],
            [
                'quantity_code' => 'PKG',
                'quantity_name' => 'Packages',
                'quantity_category' => 'Count',
                'unit_of_measure' => 'Packages',
                'unit_symbol' => 'pkgs',
                'base_unit' => 'pieces',
                'conversion_factor' => 1.0,
                'decimal_places' => 0,
                'description' => 'Count of packages or parcels',
                'calculation_method' => 'Count of packaged units',
                'applicable_cargo_types' => ['General Cargo', 'Break Bulk', 'LCL'],
                'industry_standards' => ['Universal'],
                'common_ranges' => ['min' => 1, 'max' => 50000],
                'validation_rules' => ['positive_integer'],
                'display_format' => '%.0f pkgs',
                'reporting_category' => 'Package Count',
                'is_weight_based' => false,
                'is_volume_based' => false,
                'is_count_based' => true,
                'is_dimension_based' => false,
                'allows_fractions' => false,
                'requires_dimensions' => false,
                'auto_calculate' => false,
                'is_billable' => true,
                'billing_multiplier' => 1.0,
                'minimum_chargeable' => 1.0,
                'rounding_method' => 'up',
                'is_standard' => true,
                'is_active' => true,
                'sort_order' => 8,
                'notes' => 'Count of individual packages or parcels'
            ],

            // Liquid Measurements
            [
                'quantity_code' => 'LTR',
                'quantity_name' => 'Liters',
                'quantity_category' => 'Liquid',
                'unit_of_measure' => 'Liters',
                'unit_symbol' => 'L',
                'base_unit' => 'liters',
                'conversion_factor' => 1.0,
                'decimal_places' => 2,
                'description' => 'Liquid volume measurement in liters',
                'calculation_method' => 'Direct liquid volume measurement',
                'applicable_cargo_types' => ['Liquid Bulk', 'Chemicals', 'Fuel'],
                'industry_standards' => ['SI Units', 'ISO 80000-3'],
                'common_ranges' => ['min' => 1, 'max' => 1000000000],
                'validation_rules' => ['positive_number'],
                'display_format' => '%.2f L',
                'reporting_category' => 'Liquid Volume',
                'is_weight_based' => false,
                'is_volume_based' => true,
                'is_count_based' => false,
                'is_dimension_based' => false,
                'allows_fractions' => true,
                'requires_dimensions' => false,
                'auto_calculate' => false,
                'is_billable' => true,
                'billing_multiplier' => 1.0,
                'minimum_chargeable' => 1.0,
                'rounding_method' => 'nearest',
                'is_standard' => true,
                'is_active' => true,
                'sort_order' => 9,
                'notes' => 'Standard liquid measurement unit'
            ],

            // Dimensional Cargo
            [
                'quantity_code' => 'SQM',
                'quantity_name' => 'Square Meters',
                'quantity_category' => 'Area',
                'unit_of_measure' => 'Square Meter',
                'unit_symbol' => 'm²',
                'base_unit' => 'sqm',
                'conversion_factor' => 1.0,
                'decimal_places' => 2,
                'description' => 'Area measurement for flat cargo',
                'calculation_method' => 'Length × Width in meters',
                'applicable_cargo_types' => ['Flat Rack', 'Steel Sheets', 'Lumber'],
                'industry_standards' => ['SI Units'],
                'common_ranges' => ['min' => 0.01, 'max' => 10000],
                'validation_rules' => ['positive_number'],
                'display_format' => '%.2f m²',
                'reporting_category' => 'Area',
                'is_weight_based' => false,
                'is_volume_based' => false,
                'is_count_based' => false,
                'is_dimension_based' => true,
                'allows_fractions' => true,
                'requires_dimensions' => true,
                'auto_calculate' => true,
                'is_billable' => true,
                'billing_multiplier' => 1.0,
                'minimum_chargeable' => 0.01,
                'rounding_method' => 'up',
                'is_standard' => true,
                'is_active' => true,
                'sort_order' => 10,
                'notes' => 'Used for flat cargo like steel sheets or lumber'
            ],

            // Special Units
            [
                'quantity_code' => 'RT',
                'quantity_name' => 'Revenue Ton',
                'quantity_category' => 'Weight',
                'unit_of_measure' => 'Revenue Ton',
                'unit_symbol' => 'RT',
                'base_unit' => 'kg',
                'conversion_factor' => 1000.0,
                'decimal_places' => 3,
                'description' => 'Billing unit - higher of weight or volume ton',
                'calculation_method' => 'Max(Weight MT, Volume/1000)',
                'applicable_cargo_types' => ['General Cargo', 'Break Bulk', 'LCL'],
                'industry_standards' => ['Freight Industry'],
                'common_ranges' => ['min' => 0.001, 'max' => 50000],
                'validation_rules' => ['positive_number'],
                'display_format' => '%.3f RT',
                'reporting_category' => 'Billing Weight',
                'is_weight_based' => true,
                'is_volume_based' => true,
                'is_count_based' => false,
                'is_dimension_based' => false,
                'allows_fractions' => true,
                'requires_dimensions' => false,
                'auto_calculate' => true,
                'is_billable' => true,
                'billing_multiplier' => 1.0,
                'minimum_chargeable' => 0.001,
                'rounding_method' => 'up',
                'is_standard' => true,
                'is_active' => true,
                'sort_order' => 11,
                'notes' => 'Higher of weight or volume for billing purposes'
            ],

            // Length Measurements
            [
                'quantity_code' => 'M',
                'quantity_name' => 'Meters',
                'quantity_category' => 'Length',
                'unit_of_measure' => 'Meter',
                'unit_symbol' => 'm',
                'base_unit' => 'meters',
                'conversion_factor' => 1.0,
                'decimal_places' => 2,
                'description' => 'Linear measurement in meters',
                'calculation_method' => 'Direct linear measurement',
                'applicable_cargo_types' => ['Steel', 'Pipes', 'Lumber', 'Cable'],
                'industry_standards' => ['SI Units'],
                'common_ranges' => ['min' => 0.01, 'max' => 10000],
                'validation_rules' => ['positive_number'],
                'display_format' => '%.2f m',
                'reporting_category' => 'Length',
                'is_weight_based' => false,
                'is_volume_based' => false,
                'is_count_based' => false,
                'is_dimension_based' => true,
                'allows_fractions' => true,
                'requires_dimensions' => false,
                'auto_calculate' => false,
                'is_billable' => true,
                'billing_multiplier' => 1.0,
                'minimum_chargeable' => 0.01,
                'rounding_method' => 'nearest',
                'is_standard' => true,
                'is_active' => true,
                'sort_order' => 12,
                'notes' => 'Linear measurement for long cargo'
            ],

            // Imperial Weight (for US/UK markets)
            [
                'quantity_code' => 'LB',
                'quantity_name' => 'Pounds',
                'quantity_category' => 'Weight',
                'unit_of_measure' => 'Pound',
                'unit_symbol' => 'lb',
                'base_unit' => 'kg',
                'conversion_factor' => 0.453592,
                'decimal_places' => 2,
                'description' => 'Imperial weight measurement in pounds',
                'calculation_method' => 'Weight measurement in imperial pounds',
                'applicable_cargo_types' => ['General Cargo', 'Air Cargo'],
                'industry_standards' => ['Imperial Units'],
                'common_ranges' => ['min' => 0.1, 'max' => 500000],
                'validation_rules' => ['positive_number'],
                'display_format' => '%.2f lb',
                'reporting_category' => 'Gross Weight',
                'is_weight_based' => true,
                'is_volume_based' => false,
                'is_count_based' => false,
                'is_dimension_based' => false,
                'allows_fractions' => true,
                'requires_dimensions' => false,
                'auto_calculate' => false,
                'is_billable' => true,
                'billing_multiplier' => 1.0,
                'minimum_chargeable' => 0.1,
                'rounding_method' => 'nearest',
                'is_standard' => false,
                'is_active' => true,
                'sort_order' => 13,
                'notes' => 'Imperial weight unit for US and UK markets'
            ],

            // Time-based measurements (for services)
            [
                'quantity_code' => 'HR',
                'quantity_name' => 'Hours',
                'quantity_category' => 'Time',
                'unit_of_measure' => 'Hour',
                'unit_symbol' => 'hr',
                'base_unit' => 'hours',
                'conversion_factor' => 1.0,
                'decimal_places' => 2,
                'description' => 'Time measurement in hours for services',
                'calculation_method' => 'Direct time measurement',
                'applicable_cargo_types' => ['Services', 'Labor', 'Equipment Rental'],
                'industry_standards' => ['Universal'],
                'common_ranges' => ['min' => 0.25, 'max' => 10000],
                'validation_rules' => ['positive_number'],
                'display_format' => '%.2f hr',
                'reporting_category' => 'Service Time',
                'is_weight_based' => false,
                'is_volume_based' => false,
                'is_count_based' => false,
                'is_dimension_based' => false,
                'allows_fractions' => true,
                'requires_dimensions' => false,
                'auto_calculate' => false,
                'is_billable' => true,
                'billing_multiplier' => 1.0,
                'minimum_chargeable' => 0.25,
                'rounding_method' => 'nearest',
                'is_standard' => true,
                'is_active' => true,
                'sort_order' => 14,
                'notes' => 'Time-based billing for services and labor'
            ],

            // Pallets (common in warehousing)
            [
                'quantity_code' => 'PLT',
                'quantity_name' => 'Pallets',
                'quantity_category' => 'Count',
                'unit_of_measure' => 'Pallet',
                'unit_symbol' => 'plt',
                'base_unit' => 'pieces',
                'conversion_factor' => 1.0,
                'decimal_places' => 0,
                'description' => 'Standard pallet count for warehousing',
                'calculation_method' => 'Count of standard pallets',
                'applicable_cargo_types' => ['General Cargo', 'Warehousing', 'Distribution'],
                'industry_standards' => ['ISO 6780'],
                'common_ranges' => ['min' => 1, 'max' => 10000],
                'validation_rules' => ['positive_integer'],
                'display_format' => '%.0f plt',
                'reporting_category' => 'Pallet Count',
                'is_weight_based' => false,
                'is_volume_based' => false,
                'is_count_based' => true,
                'is_dimension_based' => false,
                'allows_fractions' => false,
                'requires_dimensions' => false,
                'auto_calculate' => false,
                'is_billable' => true,
                'billing_multiplier' => 1.0,
                'minimum_chargeable' => 1.0,
                'rounding_method' => 'up',
                'is_standard' => true,
                'is_active' => true,
                'sort_order' => 15,
                'notes' => 'Standard pallet units for warehousing operations'
            ],

            // Test/Demo quantity type (inactive)
            [
                'quantity_code' => 'TEST',
                'quantity_name' => 'Test Quantity Type',
                'quantity_category' => 'Count',
                'unit_of_measure' => 'Test Unit',
                'unit_symbol' => 'test',
                'base_unit' => 'pieces',
                'conversion_factor' => 1.0,
                'decimal_places' => 0,
                'description' => 'Test quantity type for development and testing',
                'calculation_method' => 'Test calculation method',
                'applicable_cargo_types' => ['Test Cargo'],
                'industry_standards' => ['Test Standard'],
                'common_ranges' => ['min' => 1, 'max' => 100],
                'validation_rules' => ['positive_integer'],
                'display_format' => '%.0f test',
                'reporting_category' => 'Test Category',
                'is_weight_based' => false,
                'is_volume_based' => false,
                'is_count_based' => true,
                'is_dimension_based' => false,
                'allows_fractions' => false,
                'requires_dimensions' => false,
                'auto_calculate' => false,
                'is_billable' => false,
                'billing_multiplier' => 0.0,
                'minimum_chargeable' => 0.0,
                'rounding_method' => 'nearest',
                'is_standard' => false,
                'is_active' => false,
                'sort_order' => 999,
                'notes' => 'Inactive test quantity type for development purposes'
            ]
        ];

        foreach ($quantityTypes as $quantityType) {
            QuantityType::create($quantityType);
        }

        $this->command->info('QuantityType seeder completed successfully!');
        $this->command->info('Created ' . count($quantityTypes) . ' quantity types.');
        $this->command->info('Including: 15 active standard types and 1 inactive test type.');
    }
}
