<?php

namespace Database\Seeders;

use App\Models\QuantityType;
use Illuminate\Database\Seeder;

class QuantityTypeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $quantityTypes = [
            // Container Units
            [
                'quantity_code' => 'TEU',
                'quantity_name' => 'Twenty-foot Equivalent Unit',
                'quantity_category' => 'Container',
                'unit_of_measure' => 'Container',
                'unit_symbol' => 'TEU',
                'base_unit' => 'TEU',
                'conversion_factor' => 1.0,
                'decimal_places' => 0,
                'description' => 'Standard 20-foot container equivalent unit measurement',
                'calculation_method' => 'Count of 20ft container equivalents',
                'applicable_cargo_types' => ['Containers', 'General Cargo'],
                'industry_standards' => ['ISO 668', 'CSC Convention'],
                'common_ranges' => ['min' => 1, 'max' => 50000],
                'validation_rules' => ['positive_integer'],
                'display_format' => '%.0f TEU',
                'reporting_category' => 'Container Volume',
                'is_weight_based' => false,
                'is_volume_based' => true,
                'is_count_based' => true,
                'is_dimension_based' => false,
                'allows_fractions' => false,
                'requires_dimensions' => false,
                'auto_calculate' => false,
                'is_billable' => true,
                'billing_multiplier' => 1.0,
                'minimum_chargeable' => 1.0,
                'rounding_method' => 'up',
                'is_standard' => true,
                'is_active' => true,
                'sort_order' => 1,
                'notes' => 'Primary container measurement unit in shipping industry'
            ],
            [
                'quantity_code' => 'FEU',
                'quantity_name' => 'Forty-foot Equivalent Unit',
                'quantity_category' => 'Container',
                'unit_of_measure' => 'Container',
                'unit_symbol' => 'FEU',
                'base_unit' => 'TEU',
                'conversion_factor' => 2.0,
                'decimal_places' => 0,
                'description' => 'Standard 40-foot container unit',
                'calculation_method' => 'Count of 40ft containers',
                'applicable_cargo_types' => ['Containers', 'General Cargo'],
                'industry_standards' => ['ISO 668', 'CSC Convention'],
                'common_ranges' => ['min' => 1, 'max' => 25000],
                'validation_rules' => ['positive_integer'],
                'display_format' => '%.0f FEU',
                'reporting_category' => 'Container Volume',
                'is_weight_based' => false,
                'is_volume_based' => true,
                'is_count_based' => true,
                'is_dimension_based' => false,
                'allows_fractions' => false,
                'requires_dimensions' => false,
                'auto_calculate' => false,
                'is_billable' => true,
                'billing_multiplier' => 2.0,
                'minimum_chargeable' => 1.0,
                'rounding_method' => 'up',
                'is_standard' => true,
                'is_active' => true,
                'sort_order' => 2,
                'notes' => '40-foot container standard measurement'
            ],

            // Weight Measurements
            [
                'quantity_code' => 'KG',
                'quantity_name' => 'Kilogram',
                'quantity_category' => 'Weight',
                'unit_of_measure' => 'Kilogram',
                'unit_symbol' => 'kg',
                'base_unit' => 'kg',
                'conversion_factor' => 1.0,
                'decimal_places' => 3,
                'description' => 'Metric unit of mass measurement',
                'calculation_method' => 'Direct weight measurement',
                'applicable_cargo_types' => ['General Cargo', 'Bulk', 'Containers', 'Break Bulk'],
                'industry_standards' => ['SI Units', 'ISO 80000-4'],
                'common_ranges' => ['min' => 0.001, 'max' => 100000000],
                'validation_rules' => ['positive_number'],
                'display_format' => '%.3f kg',
                'reporting_category' => 'Gross Weight',
                'is_weight_based' => true,
                'is_volume_based' => false,
                'is_count_based' => false,
                'is_dimension_based' => false,
                'allows_fractions' => true,
                'requires_dimensions' => false,
                'auto_calculate' => false,
                'is_billable' => true,
                'billing_multiplier' => 1.0,
                'minimum_chargeable' => 0.001,
                'rounding_method' => 'nearest',
                'is_standard' => true,
                'is_active' => true,
                'sort_order' => 3,
                'notes' => 'Standard metric weight unit'
            ],
            [
                'quantity_code' => 'MT',
                'quantity_name' => 'Metric Ton',
                'quantity_category' => 'Weight',
                'unit_of_measure' => 'Metric Ton',
                'unit_symbol' => 'MT',
                'base_unit' => 'kg',
                'conversion_factor' => 1000.0,
                'decimal_places' => 3,
                'description' => 'Metric ton (1000 kg) for large cargo weights',
                'calculation_method' => 'Weight in thousands of kilograms',
                'applicable_cargo_types' => ['Bulk', 'Heavy Cargo', 'Break Bulk'],
                'industry_standards' => ['SI Units', 'ISO 80000-4'],
                'common_ranges' => ['min' => 0.001, 'max' => 100000],
                'validation_rules' => ['positive_number'],
                'display_format' => '%.3f MT',
                'reporting_category' => 'Gross Weight',
                'is_weight_based' => true,
                'is_volume_based' => false,
                'is_count_based' => false,
                'is_dimension_based' => false,
                'allows_fractions' => true,
                'requires_dimensions' => false,
                'auto_calculate' => false,
                'is_billable' => true,
                'billing_multiplier' => 1.0,
                'minimum_chargeable' => 0.001,
                'rounding_method' => 'nearest',
                'is_standard' => true,
                'is_active' => true,
                'sort_order' => 4,
                'notes' => 'Used for heavy cargo and bulk commodities'
            ],

            // Volume Measurements
            [
                'quantity_code' => 'CBM',
                'quantity_name' => 'Cubic Meter',
                'quantity_category' => 'Volume',
                'unit_of_measure' => 'Cubic Meter',
                'unit_symbol' => 'm³',
                'base_unit' => 'cbm',
                'conversion_factor' => 1.0,
                'decimal_places' => 3,
                'description' => 'Standard volume measurement in cubic meters',
                'calculation_method' => 'Length × Width × Height in meters',
                'applicable_cargo_types' => ['General Cargo', 'Break Bulk', 'LCL'],
                'industry_standards' => ['SI Units', 'ISO 80000-3'],
                'common_ranges' => ['min' => 0.001, 'max' => 50000],
                'validation_rules' => ['positive_number'],
                'display_format' => '%.3f m³',
                'reporting_category' => 'Volume',
                'is_weight_based' => false,
                'is_volume_based' => true,
                'is_count_based' => false,
                'is_dimension_based' => true,
                'allows_fractions' => true,
                'requires_dimensions' => true,
                'auto_calculate' => true,
                'is_billable' => true,
                'billing_multiplier' => 1.0,
                'minimum_chargeable' => 0.001,
                'rounding_method' => 'up',
                'is_standard' => true,
                'is_active' => true,
                'sort_order' => 5,
                'notes' => 'Standard volumetric measurement for LCL and break bulk'
            ],
            [
                'quantity_code' => 'CFT',
                'quantity_name' => 'Cubic Feet',
                'quantity_category' => 'Volume',
                'unit_of_measure' => 'Cubic Feet',
                'unit_symbol' => 'ft³',
                'base_unit' => 'cbm',
                'conversion_factor' => 0.0283168,
                'decimal_places' => 2,
                'description' => 'Imperial volume measurement in cubic feet',
                'calculation_method' => 'Length × Width × Height in feet',
                'applicable_cargo_types' => ['General Cargo', 'Break Bulk', 'Air Cargo'],
                'industry_standards' => ['Imperial Units'],
                'common_ranges' => ['min' => 0.1, 'max' => 100000],
                'validation_rules' => ['positive_number'],
                'display_format' => '%.2f ft³',
                'reporting_category' => 'Volume',
                'is_weight_based' => false,
                'is_volume_based' => true,
                'is_count_based' => false,
                'is_dimension_based' => true,
                'allows_fractions' => true,
                'requires_dimensions' => true,
                'auto_calculate' => true,
                'is_billable' => true,
                'billing_multiplier' => 1.0,
                'minimum_chargeable' => 0.1,
                'rounding_method' => 'up',
                'is_standard' => false,
                'is_active' => true,
                'sort_order' => 6,
                'notes' => 'Imperial volume unit commonly used in North America'
            ],

            // Count/Piece Measurements
            [
                'quantity_code' => 'PCS',
                'quantity_name' => 'Pieces',
                'quantity_category' => 'Count',
                'unit_of_measure' => 'Pieces',
                'unit_symbol' => 'pcs',
                'base_unit' => 'pieces',
                'conversion_factor' => 1.0,
                'decimal_places' => 0,
                'description' => 'Individual item count',
                'calculation_method' => 'Physical count of individual items',
                'applicable_cargo_types' => ['General Cargo', 'Break Bulk', 'Project Cargo'],
                'industry_standards' => ['Universal'],
                'common_ranges' => ['min' => 1, 'max' => 1000000],
                'validation_rules' => ['positive_integer'],
                'display_format' => '%.0f pcs',
                'reporting_category' => 'Item Count',
                'is_weight_based' => false,
                'is_volume_based' => false,
                'is_count_based' => true,
                'is_dimension_based' => false,
                'allows_fractions' => false,
                'requires_dimensions' => false,
                'auto_calculate' => false,
                'is_billable' => true,
                'billing_multiplier' => 1.0,
                'minimum_chargeable' => 1.0,
                'rounding_method' => 'up',
                'is_standard' => true,
                'is_active' => true,
                'sort_order' => 7,
                'notes' => 'Basic unit count for individual items'
            ],
            [
                'quantity_code' => 'PKG',
                'quantity_name' => 'Packages',
                'quantity_category' => 'Count',
                'unit_of_measure' => 'Packages',
                'unit_symbol' => 'pkgs',
                'base_unit' => 'pieces',
                'conversion_factor' => 1.0,
                'decimal_places' => 0,
                'description' => 'Count of packages or parcels',
                'calculation_method' => 'Count of packaged units',
                'applicable_cargo_types' => ['General Cargo', 'Break Bulk', 'LCL'],
                'industry_standards' => ['Universal'],
                'common_ranges' => ['min' => 1, 'max' => 50000],
                'validation_rules' => ['positive_integer'],
                'display_format' => '%.0f pkgs',
                'reporting_category' => 'Package Count',
                'is_weight_based' => false,
                'is_volume_based' => false,
                'is_count_based' => true,
                'is_dimension_based' => false,
                'allows_fractions' => false,
                'requires_dimensions' => false,
                'auto_calculate' => false,
                'is_billable' => true,
                'billing_multiplier' => 1.0,
                'minimum_chargeable' => 1.0,
                'rounding_method' => 'up',
                'is_standard' => true,
                'is_active' => true,
                'sort_order' => 8,
                'notes' => 'Count of individual packages or parcels'
            ],

            // Liquid Measurements
            [
                'quantity_code' => 'LTR',
                'quantity_name' => 'Liters',
                'quantity_category' => 'Liquid',
                'unit_of_measure' => 'Liters',
                'unit_symbol' => 'L',
                'base_unit' => 'liters',
                'conversion_factor' => 1.0,
                'decimal_places' => 2,
                'description' => 'Liquid volume measurement in liters',
                'calculation_method' => 'Direct liquid volume measurement',
                'applicable_cargo_types' => ['Liquid Bulk', 'Chemicals', 'Fuel'],
                'industry_standards' => ['SI Units', 'ISO 80000-3'],
                'common_ranges' => ['min' => 1, 'max' => 1000000000],
                'validation_rules' => ['positive_number'],
                'display_format' => '%.2f L',
                'reporting_category' => 'Liquid Volume',
                'is_weight_based' => false,
                'is_volume_based' => true,
                'is_count_based' => false,
                'is_dimension_based' => false,
                'allows_fractions' => true,
                'requires_dimensions' => false,
                'auto_calculate' => false,
                'is_billable' => true,
                'billing_multiplier' => 1.0,
                'minimum_chargeable' => 1.0,
                'rounding_method' => 'nearest',
                'is_standard' => true,
                'is_active' => true,
                'sort_order' => 9,
                'notes' => 'Standard liquid measurement unit'
            ],

            // Dimensional Cargo
            [
                'quantity_code' => 'SQM',
                'quantity_name' => 'Square Meters',
                'quantity_category' => 'Area',
                'unit_of_measure' => 'Square Meter',
                'unit_symbol' => 'm²',
                'base_unit' => 'sqm',
                'conversion_factor' => 1.0,
                'decimal_places' => 2,
                'description' => 'Area measurement for flat cargo',
                'calculation_method' => 'Length × Width in meters',
                'applicable_cargo_types' => ['Flat Rack', 'Steel Sheets', 'Lumber'],
                'industry_standards' => ['SI Units'],
                'common_ranges' => ['min' => 0.01, 'max' => 10000],
                'validation_rules' => ['positive_number'],
                'display_format' => '%.2f m²',
                'reporting_category' => 'Area',
                'is_weight_based' => false,
                'is_volume_based' => false,
                'is_count_based' => false,
                'is_dimension_based' => true,
                'allows_fractions' => true,
                'requires_dimensions' => true,
                'auto_calculate' => true,
                'is_billable' => true,
                'billing_multiplier' => 1.0,
                'minimum_chargeable' => 0.01,
                'rounding_method' => 'up',
                'is_standard' => true,
                'is_active' => true,
                'sort_order' => 10,
                'notes' => 'Used for flat cargo like steel sheets or lumber'
            ],

            // Special Units
            [
                'quantity_code' => 'RT',
                'quantity_name' => 'Revenue Ton',
                'quantity_category' => 'Weight',
                'unit_of_measure' => 'Revenue Ton',
                'unit_symbol' => 'RT',
                'base_unit' => 'kg',
                'conversion_factor' => 1000.0,
                'decimal_places' => 3,
                'description' => 'Billing unit - higher of weight or volume ton',
                'calculation_method' => 'Max(Weight MT, Volume/1000)',
                'applicable_cargo_types' => ['General Cargo', 'Break Bulk', 'LCL'],
                'industry_standards' => ['Freight Industry'],
                'common_ranges' => ['min' => 0.001, 'max' => 50000],
                'validation_rules' => ['positive_number'],
                'display_format' => '%.3f RT',
                'reporting_category' => 'Billing Weight',
                'is_weight_based' => true,
                'is_volume_based' => true,
                'is_count_based' => false,
                'is_dimension_based' => false,
                'allows_fractions' => true,
                'requires_dimensions' => false,
                'auto_calculate' => true,
                'is_billable' => true,
                'billing_multiplier' => 1.0,
                'minimum_chargeable' => 0.001,
                'rounding_method' => 'up',
                'is_standard' => false,
                'is_active' => true,
                'sort_order' => 11,
                'notes' => 'Used for freight billing - higher of actual weight or volumetric weight'
            ],

            // Time-based (for storage, demurrage)
            [
                'quantity_code' => 'DAYS',
                'quantity_name' => 'Days',
                'quantity_category' => 'Time',
                'unit_of_measure' => 'Days',
                'unit_symbol' => 'days',
                'base_unit' => 'days',
                'conversion_factor' => 1.0,
                'decimal_places' => 1,
                'description' => 'Time-based measurement in days',
                'calculation_method' => 'Duration calculation in days',
                'applicable_cargo_types' => ['Storage', 'Demurrage', 'Detention'],
                'industry_standards' => ['Universal'],
                'common_ranges' => ['min' => 0.1, 'max' => 365],
                'validation_rules' => ['positive_number'],
                'display_format' => '%.1f days',
                'reporting_category' => 'Time Duration',
                'is_weight_based' => false,
                'is_volume_based' => false,
                'is_count_based' => false,
                'is_dimension_based' => false,
                'allows_fractions' => true,
                'requires_dimensions' => false,
                'auto_calculate' => true,
                'is_billable' => true,
                'billing_multiplier' => 1.0,
                'minimum_chargeable' => 1.0,
                'rounding_method' => 'up',
                'is_standard' => true,
                'is_active' => true,
                'sort_order' => 12,
                'notes' => 'Used for storage charges, demurrage, and time-based billing'
            ]
        ];

        foreach ($quantityTypes as $quantityTypeData) {
            QuantityType::create(array_merge($quantityTypeData, [
                'tenant_id' => 1 // Default tenant for seeding
            ]));
        }
    }
}
